### ISSUE TITLE
您好我在用lamp一键脚本之后安装了webmin，但是安装好之后报这个错误，这个应该如何解决？

### ISSUE THREAD

**Issue by cntel18217223380** [teddysun/lamp#10]
Failed to save enabled features : Suexec在缺省模板中被启用，但是Apache的mod_suexec模块没有安装或者没有启用。

**Comment by teddysun** [comment]
以下是 Apache 编译安装的所有模块，并没有 mod_suexec 模块。

参考网址：https://httpd.apache.org/docs/2.4/mod/

你需要重新编译 Apache，并在编译参数里加上 --enable-suexec

mod_access_compat.so
mod_actions.so
mod_alias.so
mod_allowmethods.so
mod_asis.so
mod_auth_basic.so
mod_auth_digest.so
mod_auth_form.so
mod_authn_anon.so
mod_authn_core.so
mod_authn_dbd.so
mod_authn_dbm.so
mod_authn_file.so
mod_authn_socache.so
mod_authz_core.so
mod_authz_dbd.so
mod_authz_dbm.so
mod_authz_groupfile.so
mod_authz_host.so
mod_authz_owner.so
mod_authz_user.so
mod_autoindex.so
mod_buffer.so
mod_cache_disk.so
mod_cache.so
mod_cache_socache.so
mod_cgi.so
mod_charset_lite.so
mod_data.so
mod_dav_fs.so
mod_dav_lock.so
mod_dav.so
mod_dbd.so
mod_deflate.so
mod_dialup.so
mod_dir.so
mod_dumpio.so
mod_echo.so
mod_env.so
mod_expires.so
mod_ext_filter.so
mod_file_cache.so
mod_filter.so
mod_headers.so
mod_heartbeat.so
mod_heartmonitor.so
mod_include.so
mod_info.so
mod_lbmethod_bybusyness.so
mod_lbmethod_byrequests.so
mod_lbmethod_bytraffic.so
mod_lbmethod_heartbeat.so
mod_log_config.so
mod_log_debug.so
mod_log_forensic.so
mod_logio.so
mod_macro.so
mod_mime_magic.so
mod_mime.so
mod_negotiation.so
mod_proxy_ajp.so
mod_proxy_balancer.so
mod_proxy_connect.so
mod_proxy_express.so
mod_proxy_fcgi.so
mod_proxy_fdpass.so
mod_proxy_ftp.so
mod_proxy_html.so
mod_proxy_http.so
mod_proxy_scgi.so
mod_proxy.so
mod_proxy_wstunnel.so
mod_ratelimit.so
mod_reflector.so
mod_remoteip.so
mod_reqtimeout.so
mod_request.so
mod_rewrite.so
mod_sed.so
mod_session_cookie.so
mod_session_dbd.so
mod_session.so
mod_setenvif.so
mod_slotmem_plain.so
mod_slotmem_shm.so
mod_socache_dbm.so
mod_socache_memcache.so
mod_socache_shmcb.so
mod_speling.so
mod_ssl.so
mod_status.so
mod_substitute.so
mod_unique_id.so
mod_unixd.so
mod_userdir.so
mod_usertrack.so
mod_version.so
mod_vhost_alias.so
mod_watchdog.so
mod_xml2enc.so

**Comment by cntel18217223380** [comment]
![apache](https://cloud.githubusercontent.com/assets/15363978/11736246/9c67182e-a006-11e5-91fc-961228e27b88.PNG)

我添加参数重新编译了，但还是报这个错，我想应该是因为我没有加载它，请问我应该如何设置才能让apache在运行的时候加载这个模块呢？

**Comment by teddysun** [comment]
先去以下路径看看有没有 mod_suexec 模块

**Comment by cntel18217223380** [comment]
您好，我在 /usr/local/apache/module路径下没有查到mod_suexec.so文件，我之前是修改upgrade_apache.sh这个文件然后重新编译的，但是编译好之后没有看到该文件，修改的参数已经截图，但还是没有生成mod_suexec.so这个文件，请问我接下来应该如何操作，让apache自动生成这个文件呢？还是用其它方法找到这个文件？

**Comment by cntel18217223380** [comment]
找到了有了，刚才登录错服务器不好意思。问题已解决已经编译成功，并加载模块和启动apache。
![apache](https://cloud.githubusercontent.com/assets/15363978/11751725/3b9d0eca-a076-11e5-8baf-ed7dd76acae8.PNG)
。
