### ISSUE TITLE
can't use certbot!

### ISSUE THREAD

**Issue by buzz3rs** [teddysun/lamp#100]
when i install lamp.sh i cant obtain new ssl certificates using the --apache in [certbot](https://github.com/certbot/certbot) flag getting an error that says :
Prep: Unable to run the command: apache2ctl configtest
though the [certbot](https://github.com/certbot/certbot) works just fine if i install apache2 from **apt install apache2**

but when i do that i won't be able to use full features of lamp (kod, php, phpmyadmin, etc)

**Comment by teddysun** [comment]
--apache option does not apply to direct use.
Because Apache is compile & installation

**Comment by bensonkb** [comment]
How To Use Certbot Standalone Mode to Retrieve Let's Encrypt SSL Certificates on Ubuntu 18.04 using on lamp.sh ?
