### ISSUE TITLE
Bug Urgent - Gmagick

### ISSUE THREAD

**Issue by LaTecnologia24** [teddysun/lamp#107]
I can't install your LAMP, i have tried 4 times always this error:

CPU model            : Intel(R) Xeon(R) CPU E5-1630 v4 @ 3.70GHz
Number of cores      : 8
CPU frequency        : 3699.997 MHz
Total amount of ram  : 29995 MB
Total amount of swap : 1639 MB
System uptime        : 0days, 0:0:43
Load average         : 0,63, 0,17, 0,06
OS                   : CentOS 7.6.1810
Arch                 : x86_64 (64 Bit)

Apache: httpd-2.4.37
Apache Location: /usr/local/apache

MariaDB: mariadb-10.3.11
MariaDB Location: /usr/local/mariadb

PHP: php-7.3.0
PHP Location: /usr/local/php
PHP Additional Modules:
imagick-3.4.3
gmagick-2.0.5RC1
memcached-3.0.4
libsodium-php-2.0.20
swoole-src-4.2.11

phpMyAdmin: do_not_install
KodExplorer: do_not_install

![immagine](https://user-images.githubusercontent.com/33404214/50550609-f0aaab80-0c73-11e9-85da-381e947ad4ad.png)

```
/usr/include/freetype2/freetype/freetype.h:801:37: error: ‘FT_ENCODING_PRC’ undeclared (first use in this function)
 #define ft_encoding_gb2312          FT_ENCODING_PRC
                                     ^
magick/annotate.c:1232:23: note: in expansion of macro ‘ft_encoding_gb2312’
         encoding_type=ft_encoding_gb2312;
                       ^
/usr/include/freetype2/freetype/freetype.h:801:37: note: each undeclared identifier is reported only once for each function it appears in
 #define ft_encoding_gb2312          FT_ENCODING_PRC
                                     ^
magick/annotate.c:1232:23: note: in expansion of macro ‘ft_encoding_gb2312’
         encoding_type=ft_encoding_gb2312;
                       ^
make[1]: *** [magick/magick_libGraphicsMagick_la-annotate.lo] Errore 1
make[1]: Leaving directory `/root/lamp/software/GraphicsMagick-1.3.30'
make: *** [all] Errore 2
```

**Comment by teddysun** [comment]
Please refer URL:
https://bugzilla.redhat.com/show_bug.cgi?id=1645218

It looks like a freetype2's bug. please wait RedHat fix it.

**Comment by teddysun** [comment]
You can likely patch the source of what you are trying to build to work with existing freetype header.

`sed -i "s@encoding_type=ft_encoding_gb2312@encoding_type=FT_ENCODING_GB2312@" GraphicsMagick-1.3.31/magick/annotate.c`

**Comment by LaTecnologia24** [comment]
I just use your script, how to add this command during build?

**Comment by teddysun** [comment]
modify include/php-modules.sh, function `install_php_graphicsmagick`, line 542

Before
    `cd ${GraphicsMagick_filename}`
    `error_detect "./configure --enable-shared"`
    `error_detect "make"`
    `error_detect "make install"`

After
    `cd ${GraphicsMagick_filename}`
    `sed -i "s@encoding_type=ft_encoding_gb2312@encoding_type=FT_ENCODING_GB2312@" magick/annotate.c`
    `error_detect "./configure --enable-shared"`
    `error_detect "make"`
    `error_detect "make install"`

**Comment by LaTecnologia24** [comment]
> 
> 
> You can likely patch the source of what you are trying to build to work with existing freetype header.
> 
> `sed -i "s@encoding_type=ft_encoding_gb2312@encoding_type=FT_ENCODING_GB2312@" GraphicsMagick-1.3.31/magick/annotate.c`

I just use your script, how to add this command during build?

**Comment by LaTecnologia24** [comment]
> s@encoding_type=ft_encoding_gb2312@encodi

Thank you very much as always for your availability, I wish you happy new year!

**Comment by LaTecnologia24** [comment]
After 1 month i have installed again and i have always this bug and i need any time to manually edit, why?

**Comment by majidkhan591** [comment]
Its fixed. All you need to do if you are on Centos 7 is this:

yum update freetype
