### ISSUE TITLE
Memcache Error

### ISSUE THREAD

**Issue by LaTecnologia24** [teddysun/lamp#108]
CPU model : Intel(R) Xeon(R) CPU E5-1630 v4 @ 3.70GHz
Number of cores : 8
CPU frequency : 3699.997 MHz
Total amount of ram : 29995 MB
Total amount of swap : 1639 MB
System uptime : 0days, 0:0:43
Load average : 0,63, 0,17, 0,06
OS : CentOS 7.6.1810
Arch : x86_64 (64 Bit)

Apache: httpd-2.4.37
Apache Location: /usr/local/apache

MariaDB: mariadb-10.3.11
MariaDB Location: /usr/local/mariadb

PHP: php-7.3.0
PHP Location: /usr/local/php
PHP Additional Modules:
imagick-3.4.3
gmagick-2.0.5RC1
memcached-3.0.4
libsodium-php-2.0.20
swoole-src-4.2.11

phpMyAdmin: do_not_install
KodExplorer: do_not_install

```
d -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/usr/local/include -c /root/lamp/software/memcached-3.0.4/php_memcached.c  -fPIC -DPIC -o .libs/php_memcached.o
/root/lamp/software/memcached-3.0.4/php_memcached.c: In function ‘zim_Memcached___construct’:
/root/lamp/software/memcached-3.0.4/php_memcached.c:1284:20: error: lvalue required as left operand of assignment
   GC_REFCOUNT(&le) = 1;
                    ^
make: *** [php_memcached.lo] Errore 1

+------------------+
|  ERROR DETECTED  |
+------------------+
Installation memcached-3.0.4 failed.
The Full Log is available at /root/lamp/lamp.log
Please visit website: https://lamp.sh/faq.html for help

```
![immagine](https://user-images.githubusercontent.com/33404214/50553793-6fbcd580-0cae-11e9-8694-d79ff5174304.png)

I have read this bug was fixed in 3.1 but package use 3.0.4

https://pecl.php.net/package-changelog.php?package=memcached&release=3.1.0

**Comment by teddysun** [comment]
Just updated memcached from 3.0.4 to 3.1.3, please get latest script and reinstall it.

Changelog for memcached refer URL:
https://pecl.php.net/package-changelog.php?package=memcached&release=3.1.3

**Comment by LaTecnologia24** [comment]
Thanks for all =)
