### ISSUE TITLE
lamp add with error can not find apache

### ISSUE THREAD

**Issue by hurae** [teddysun/lamp#109]
php 7.0, MySQL 8.0, any other things except for password is default.
system: ubuntu 16.04 x64
------------------------ Installed Overview -------------------------

Apache: httpd-2.4.37
wget: /usr/local/mysql/lib/libcrypto.so.1.0.0: no version information available (required by wget)
wget: /usr/local/mysql/lib/libssl.so.1.0.0: no version information available (required by wget)
wget: /usr/local/mysql/lib/libssl.so.1.0.0: no version information available (required by wget)
Default Website: http://****************************
Apache Location: /usr/local/apache

Apache Modules:  modsecurity-2.9.2

MySQL Server: mysql-8.0.13
MySQL Location: /usr/local/mysql
MySQL Data Location: /usr/local/mysql/data
MySQL Root Password: mysqlismine#21

PHP: php-7.0.33
PHP Location: /usr/local/php

PHP Modules:  ioncube_loaders imagick-3.4.3 memcached-3.1.3

phpMyAdmin: phpMyAdmin-4.8.4-all-languages
phpMyAdmin Location: /data/www/default/phpmyadmin

KodExplorer: do_not_install

---------------------------------------------------------------------
and end with:
---------------------------------------------------------------------

Starting Apache...
Starting Database...
Starting Memcached...
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:11211           0.0.0.0:*               LISTEN      100853/memcached
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1252/sshd       
tcp6       0      0 :::3306                 :::*                    LISTEN      100799/mysqld   
tcp6       0      0 :::11211                :::*                    LISTEN      100853/memcached
tcp6       0      0 :::781                  :::*                    LISTEN      1151/bcm-agent  
tcp6       0      0 :::80                   :::*                    LISTEN      100206/httpd    
tcp6       0      0 :::22                   :::*                    LISTEN      1252/sshd       
tcp6       0      0 :::33060                :::*                    LISTEN      100799/mysqld   
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path
unix  2      [ ACC ]     STREAM     LISTENING     725212   103780/systemd      /run/user/0/systemd/private
unix  2      [ ACC ]     SEQPACKET  LISTENING     10621    1/init              /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     10115    1/init              /run/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     10121    1/init              /run/lvm/lvmpolld.socket
unix  2      [ ACC ]     STREAM     LISTENING     10126    1/init              /run/lvm/lvmetad.socket
unix  2      [ ACC ]     STREAM     LISTENING     10127    1/init              /run/systemd/journal/stdout
unix  2      [ ACC ]     STREAM     LISTENING     951921   46070/2             /tmp/ssh-EpYv1N27Ss/agent.46070
unix  2      [ ACC ]     STREAM     LISTENING     14054    1/init              /var/lib/lxd/unix.socket
unix  2      [ ACC ]     STREAM     LISTENING     725292   103778/0            /tmp/ssh-P3g4dTnt0x/agent.103778
unix  2      [ ACC ]     STREAM     LISTENING     14053    1/init              /run/uuidd/request
unix  2      [ ACC ]     STREAM     LISTENING     27233    7342/iscsid         @ISCSIADM_ABSTRACT_NAMESPACE
unix  2      [ ACC ]     STREAM     LISTENING     14055    1/init              /run/snapd.socket
unix  2      [ ACC ]     STREAM     LISTENING     14056    1/init              /run/snapd-snap.socket
unix  2      [ ACC ]     STREAM     LISTENING     14059    1/init              /run/acpid.socket
unix  2      [ ACC ]     STREAM     LISTENING     14052    1/init              /var/run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     973550   100799/mysqld       /tmp/mysql.sock
unix  2      [ ACC ]     STREAM     LISTENING     973578   100799/mysqld       /tmp/mysqlx.sock

Start time     : 2019-01-01 17:02:33
Completion time: 2019-01-01 17:28:42 (Use: 26 minutes)
Welcome to visit our website: https://lamp.sh
Enjoy it
________________________________________________________________________

But then, when I try to run lamp run, the error occurs:

root@instance-test:\~#lamp add
/usr/bin/lamp: 27: /usr/bin/lamp: [[: not found
/usr/bin/lamp: 56: /usr/bin/lamp: [[: not found
-e Error: Can not find Apache, may be not installed. Please check it and try again.
root@instance-test:\~# apache
No command 'apache' found, did you mean:
 Command 'apache2' from package 'apache2-bin' (main)
apache: command not found

I need help. Thank you!

**Comment by teddysun** [comment]
sorry, it's a type miss. and now it's been fixed.
you need run `git pull` to get latest version. and replace `lamp` command like this:
```
cd ~/lamp
cp conf/lamp /usr/bin/lamp
```
