### ISSUE TITLE
PHP Max Input Vars:

### ISSUE THREAD

**Issue by brinsleyparagao** [teddysun/lamp#115]
How to increase PHP Max Input Vars to a number higher 2000 ?

**Comment by inspiretk** [comment]
From the documentation: https://github.com/teddysun/lamp You can find your php.ini file in:
* Configuration File | /usr/local/php/etc/php.ini
sudo nano /usr/local/php/etc/php.ini
* Find the line max_input_vars and change the number
max_input_vars = 8000
* (replace 8000 with what ever you want)
ctrl x to exit the nano, and y for yes save the file
* restart your apache below:
/etc/init.d/httpd restart

Hope this helps
