### ISSUE TITLE
lamp del

### ISSUE THREAD

**Issue by samste** [teddysun/lamp#116]
i install LAMP on CentOS7 x64, 
after creating with:
`lamp add mydomain.com www.mydomain.com`, the process ends successfully

but when I decide to remove this virtual host with:
`lamp del mydomain.com`, the configuration is not removed
`lamp list` "mydomain.com" it is always in the list and in the filsystem

I tried several times the result is always the same, outgoing message:
```
Usage: lamp [add | del | list]
add Create a new Apache virtual host
del Delete to Apache virtual host
list List of all Apache virtual hosts
```

only way to remove the configuration is to manually delete in /usr/local/apache/conf/vhost

**Comment by teddysun** [comment]
remove virtual host command:
`lamp del`
and enter your domain name, press Enter key...

**Comment by samste** [comment]
I got confused with the `lamp del` method, everything goes as it should go, thanks teddysun
