### ISSUE TITLE
lamp环境不支持迅雷或旋风一类的P2P软件下载

### ISSUE THREAD

**Issue by cntel18217223380** [teddysun/lamp#12]
您好，我在国内外若干个vps上安装了您的一键，但是发现有个问题，就是用IDM或者浏览器自带的下载工具下载正常，但是使用迅雷或者旋风一类的P2P下载软件就不能正常下载，请问这是怎么回事，我试过国外的vps和国内的vps都不可以。

**Comment by teddysun** [comment]
这种问题不应该是LAMP环境的问题。
IDM本身就是多线程下载工具，这个没有问题，那就代表是支持断点续传的。
