### ISSUE TITLE
手動官網下載最新版phpmyadmin登錄後主頁面下方顯示錯誤2個

### ISSUE THREAD

**Issue by erunkcx** [teddysun/lamp#124]
安裝LAMP一鍵安裝包的時候沒安裝phpmyadmin，考慮到還是手動安裝官網最新版比較好。解壓到網站根目錄後，登錄phpmyadmin，index頁下方提示

> - 配置文件现在需要一个短语密码。
     The configuration file now needs a secret passphrase (blowfish_secret).
> - 变量 $cfg['TempDir'] （./tmp/）无法访问。phpMyAdmin无法缓存模板文件，所以会运行缓慢。
      The $cfg['TempDir'] (./tmp/) is not accessible. phpMyAdmin is not able to cache templates and will be slow because of this.
![手動安裝phpmyadmin存在的問題](https://user-images.githubusercontent.com/49776261/56411695-200c1500-6271-11e9-8cac-7d2d98cfc442.png)

如何解決這兩個問題呢？如何操作？

能在[LAMP一鍵安裝包常见问题](https://lamp.sh/faq.html)里詳解一下phpmyadmin文件裏頭的配置文檔config.sample.inc.php各個項目應該怎麼填寫碼？

**Comment by teddysun** [comment]
脚本里安装的就是目前的最新版。

至于手动安装过程，首先需要的是配置文件 config.inc.php，这个在 LAMP 的 conf 目录下有，直接复制到 phpMyAdmin 的安装目录下就行。
其次，需要将 phpMyAdmin 自带的数据库导入 MySQL 中，这个自带数据库的 SQL 文件位于 phpMyAdmin 安装目录下的 sql 目录下，create_tables.sql 就是了。
在 Shell 里手动执命令导入该 SQL 文件即可。
`mysql -uroot -p${dbrootpwd} < ${phpmyadmin_root_dir}/sql/create_tables.sql `

${dbrootpwd} 是你的 MySQL root 用户密码。
${phpmyadmin_root_dir} 是你的 phpMyAdmin 安装根目录

**Comment by erunkcx** [comment]
非也，腳本里安裝的是phpMyAdmin 4.8.1，非最新版。

**Comment by teddysun** [comment]
那是因为没有更新到最新版的脚本。
phpMyAdmin 在不断更新，与此同时，脚本也是在不断更新的。
