### ISSUE TITLE
使用lamp自带的的ssl安装ssl证书一直失败！！！

### ISSUE THREAD

**Issue by 1pn** [teddysun/lamp#128]
全新的系统，azure的debian9，安装root下安装lamp，选项全默认，安装lamp结束后lamp add，全部按照交互的进行，最后一步选了2，运行了一会提示失败！
域名已经解析并且生效，服务器是azure东亚的Debian9，很想知道什么原因，在这里失败很多次了，在电报群也问了但是没人回答，大家的态度也极差根本不是为了解决问题而回答就只是为了批评而回答，希望在这里能得到解答。
附上lamp add后的全部信息，希望能得到解答！！！困扰很久了！！

root@xyzlrcxyz:/home/xyzlrcxyz/lamp# lamp add
Please enter server names (for example: lamp.sh www.lamp.sh): xyz.lrc.xyz
Please enter website root directory(default:/data/www/xyz.lrc.xyz): 
website root directory: /data/www/xyz.lrc.xyz

Please enter Administrator Email address: nlnrnc@gmail.com
Administrator Email address:nlnrnc@gmail.com

Do you want to create a database and mysql user with same name? [y/n]:y
Please enter your MySQL root password:lamp.sh
mysql: [Warning] Using a password on the command line interface can be insecure.
Please enter the database name:xyzlrcxyz
Please set the password for user xyzlrcxyz:xyzlrcxyz

Virtual host [xyz.lrc.xyz] has been created
Website root directory is: /data/www/xyz.lrc.xyz
mysql: [Warning] Using a password on the command line interface can be insecure.
Database [xyzlrcxyz] and mysql user [xyzlrcxyz] has been created
Reloading the apache config file...
Syntax OK
Reload succeed

Do you want to add a SSL certificate? [y/n]:y
1. Use your own SSL Certificate and Key
2. Use Let's Encrypt CA to create SSL Certificate and Key
3. Use Buypass.com CA to create SSL Certificate and Key
Please enter 1 or 2 or 3: 2
You chosen Let's Encrypt CA, and it will be processed automatically

Do you want force redirection from HTTP to HTTPS? [y/n]:y
You chosen force redirection from HTTP to HTTPS, and it will be processed automatically

Starting create Let's Encrypt SSL Certificate...
Bootstrapping dependencies for Debian-based OSes... (you can skip this with --no-bootstrap)
Ign:1 http://debian-archive.trafficmanager.net/debian stretch InRelease
Hit:2 http://debian-archive.trafficmanager.net/debian-security stretch/updates InRelease
Hit:3 http://debian-archive.trafficmanager.net/debian stretch-updates InRelease
Hit:4 http://debian-archive.trafficmanager.net/debian stretch-backports InRelease
Hit:5 http://debian-archive.trafficmanager.net/debian stretch Release
Reading package lists... Done                      
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ca-certificates is already the newest version (20161130+nmu1+deb9u1).
gcc is already the newest version (4:6.3.0-4).
libssl-dev is already the newest version (1.1.0j-1~deb9u1).
openssl is already the newest version (1.1.0j-1~deb9u1).
python is already the newest version (2.7.13-2).
python-dev is already the newest version (2.7.13-2).
The following additional packages will be installed:
  python-pip-whl python-pkg-resources python3-virtualenv
Suggested packages:
  augeas-doc augeas-tools python-setuptools
The following NEW packages will be installed:
  augeas-lenses libaugeas0 libffi-dev python-pip-whl python-pkg-resources
  python-virtualenv python3-virtualenv virtualenv
0 upgraded, 8 newly installed, 0 to remove and 10 not upgraded.
Need to get 2572 kB of archives.
After this operation, 5276 kB of additional disk space will be used.
Get:1 http://debian-archive.trafficmanager.net/debian stretch/main amd64 augeas-lenses all 1.8.0-1+deb9u1 [420 kB]
Get:2 http://debian-archive.trafficmanager.net/debian stretch/main amd64 libaugeas0 amd64 1.8.0-1+deb9u1 [288 kB]
Get:3 http://debian-archive.trafficmanager.net/debian stretch/main amd64 libffi-dev amd64 3.2.1-6 [161 kB]
Get:4 http://debian-archive.trafficmanager.net/debian stretch/main amd64 python-pip-whl all 9.0.1-2+deb9u1 [1399 kB]
Get:5 http://debian-archive.trafficmanager.net/debian stretch/main amd64 python-pkg-resources all 33.1.1-1 [166 kB]
Get:6 http://debian-archive.trafficmanager.net/debian stretch/main amd64 python-virtualenv all 15.1.0+ds-1 [61.1 kB]
Get:7 http://debian-archive.trafficmanager.net/debian stretch/main amd64 python3-virtualenv all 15.1.0+ds-1 [57.7 kB]
Get:8 http://debian-archive.trafficmanager.net/debian stretch/main amd64 virtualenv all 15.1.0+ds-1 [19.7 kB]
Fetched 2572 kB in 0s (5084 kB/s)      
Selecting previously unselected package augeas-lenses.
(Reading database ... 42666 files and directories currently installed.)
Preparing to unpack .../0-augeas-lenses_1.8.0-1+deb9u1_all.deb ...
Unpacking augeas-lenses (1.8.0-1+deb9u1) ...
Selecting previously unselected package libaugeas0.
Preparing to unpack .../1-libaugeas0_1.8.0-1+deb9u1_amd64.deb ...
Unpacking libaugeas0 (1.8.0-1+deb9u1) ...
Selecting previously unselected package libffi-dev:amd64.
Preparing to unpack .../2-libffi-dev_3.2.1-6_amd64.deb ...
Unpacking libffi-dev:amd64 (3.2.1-6) ...
Selecting previously unselected package python-pip-whl.
Preparing to unpack .../3-python-pip-whl_9.0.1-2+deb9u1_all.deb ...
Unpacking python-pip-whl (9.0.1-2+deb9u1) ...
Selecting previously unselected package python-pkg-resources.
Preparing to unpack .../4-python-pkg-resources_33.1.1-1_all.deb ...
Unpacking python-pkg-resources (33.1.1-1) ...
Selecting previously unselected package python-virtualenv.
Preparing to unpack .../5-python-virtualenv_15.1.0+ds-1_all.deb ...
Unpacking python-virtualenv (15.1.0+ds-1) ...
Selecting previously unselected package python3-virtualenv.
Preparing to unpack .../6-python3-virtualenv_15.1.0+ds-1_all.deb ...
Unpacking python3-virtualenv (15.1.0+ds-1) ...
Selecting previously unselected package virtualenv.
Preparing to unpack .../7-virtualenv_15.1.0+ds-1_all.deb ...
Unpacking virtualenv (15.1.0+ds-1) ...
Setting up python-pip-whl (9.0.1-2+deb9u1) ...
Setting up libffi-dev:amd64 (3.2.1-6) ...
Setting up python-pkg-resources (33.1.1-1) ...
Processing triggers for libc-bin (2.24-11+deb9u4) ...
Setting up python3-virtualenv (15.1.0+ds-1) ...
Setting up augeas-lenses (1.8.0-1+deb9u1) ...
Setting up python-virtualenv (15.1.0+ds-1) ...
Setting up virtualenv (15.1.0+ds-1) ...
Setting up libaugeas0 (1.8.0-1+deb9u1) ...
Processing triggers for libc-bin (2.24-11+deb9u4) ...
WARNING: unable to check for updates.
Creating virtual environment...
Installing Python packages...
Traceback (most recent call last):
  File "/tmp/tmp.sqikCkHMeM/pipstrap.py", line 177, in <module>
    sys.exit(main())
  File "/tmp/tmp.sqikCkHMeM/pipstrap.py", line 158, in main
    for path, digest in PACKAGES]
  File "/tmp/tmp.sqikCkHMeM/pipstrap.py", line 117, in hashed_download
    response = opener(using_https=parsed_url.scheme == 'https').open(url)
  File "/usr/lib64/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib64/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
Error: Create Let's Encrypt SSL Certificate failed.

**Comment by hyuhui** [comment]
试下运行

export PYTHONHTTPSVERIFY=0
