### ISSUE TITLE
configure: error: Unable to detect ICU prefix or /usr/bin/icu-config failed.

### ISSUE THREAD

**Issue by srisy** [teddysun/lamp#130]
安装时报错：configure: error: Unable to detect ICU prefix or /usr/bin/icu-config failed.
libicu-dev已安装最新版，请教如何解决，thank u
![image](https://user-images.githubusercontent.com/8347867/58161452-dcaf2700-7cb2-11e9-9cf2-ab7f09ac16fb.png)

![image](https://user-images.githubusercontent.com/8347867/58161296-9659c800-7cb2-11e9-9501-92b1d626cd66.png)

**Comment by DiamondSystems** [comment]
+

**Comment by weinsheimer** [comment]
刚刚碰到同样问题
环境：
CPU model            : Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
Number of cores      : 1
CPU frequency        : 2500.000 MHz
Total amount of ram  : 996 MB
Total amount of swap : 0 MB
System uptime        : 0days, 4:22:26
Load average         : 0.23, 0.75, 0.54
OS                   : Debian GNU/Linux 9
Arch                 : x86_64 (64 Bit)
Kernel               : 4.9.0-11-amd64
