### ISSUE TITLE
System time changes after installation

### ISSUE THREAD

**Issue by usernope** [teddysun/lamp#131]
After running the installer on my linux system my clock time has changed to the current time in China. Why is this?

**Comment by teddysun** [comment]
Hello，default setting is 
`ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime`

if you want to change it, you can delete `/etc/localtime` file, and make a symbolic like below.
for example:
`ln -s /usr/share/zoneinfo/Asia/Tokyo /etc/localtime`

**Comment by usernope** [comment]
Thanks, whats the reason for having that setting added as part of the install?
