### ISSUE TITLE
How to remove memcached and its PHP plugin?

### ISSUE THREAD

**Issue by jazzi** [teddysun/lamp#133]
I chose memcached with PHP when install LAMP, and now found it means little to my small website, then how to remove it? 

Thank you.

**Comment by teddysun** [comment]
1. Delete `/usr/local/php/php.d/memcached.ini` and restart Apache.
2. `/etc/init.d/memcached stop` if memcached is running and delete memcached like below:
`rm -f /etc/init.d/memcached`
`rm -f /usr/bin/memcached`
`rm -fr /usr/local/memcached`

**Comment by jazzi** [comment]
Thank you very much.
