### ISSUE TITLE
PHP7.2与7.3安装失败

### ISSUE THREAD

**Issue by ngfchl** [teddysun/lamp#134]
在百度云的服务器上安装lamp时php7.2和7.3都安装失败，主机内存1G，实际991，架了-disable-fileinfo也无法安装，安装7.1成功，不知道为何

**Comment by linhaii** [comment]
我也遇到了，上面的报错信息提示我：内存问题。我的主机内存也是1G，然后我又建立了1G的swap，再安装就成功了。

**Comment by ngfchl** [comment]
确实是内存的事，很多程序都要求2G以上内存了。。




------------------ 原始邮件 ------------------
发件人: "Amitabha"<notifications@github.com>;
发送时间: 2019年8月22日(星期四) 中午1:09
收件人: "teddysun/lamp"<lamp@noreply.github.com>;
抄送: "不弃"<328176843@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [teddysun/lamp] PHP7.2与7.3安装失败 (#134)




我也遇到了，上面的报错信息提示我：内存问题。我的主机内存也是1G，然后我又建立了1G的swap，再安装就成功了。
