### ISSUE TITLE
有可选扩展有单独命令吗

### ISSUE THREAD

**Issue by agongx** [teddysun/lamp#149]
安装完后，想添加没装的可选扩展，要重新选从头安装吗

**Comment by bensonkb** [comment]
> 安装完后，想添加没装的可选扩展，要重新选从头安装吗

Hope the Google Translation is Correct ?

> After installation, if you want to add optional extensions that are not installed, do you want to re-select them from scratch?

Yes we need to remove and start from the [scratch]Same iisue is attached.(https://github.com/teddysun/lamp/issues/150#issue-507576958).
