### ISSUE TITLE
error installing php \ debian 10

### ISSUE THREAD

**Issue by neploho** [teddysun/lamp#155]
+------------------+
|  ERROR DETECTED  |
+------------------+
Installation php-7.2.25 failed.
The Full Log is available at /home/web/lamp/lamp.log
Please visit website: https://lamp.sh/faq.html for help
)) #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11)
        Memery:
                      total        used        free      shared  buff/cache   available
Mem:          15932         387        8577           8        6967       15208
Swap:         16272           0       16272
        Disk:
        Filesystem      Size  Used Avail Use% Mounted on
sysfs              0     0     0    - /sys
proc               0     0     0    - /proc
udev            7.8G     0  7.8G   0% /dev
devpts             0     0     0    - /dev/pts
tmpfs           1.6G  8.7M  1.6G   1% /run
/dev/sda1       1.8T   31G  1.7T   2% /
securityfs         0     0     0    - /sys/kernel/security
tmpfs           7.8G     0  7.8G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup
cgroup2            0     0     0    - /sys/fs/cgroup/unified
cgroup             0     0     0    - /sys/fs/cgroup/systemd
pstore             0     0     0    - /sys/fs/pstore
bpf                0     0     0    - /sys/fs/bpf
cgroup             0     0     0    - /sys/fs/cgroup/cpu,cpuacct
cgroup             0     0     0    - /sys/fs/cgroup/freezer
cgroup             0     0     0    - /sys/fs/cgroup/perf_event
cgroup             0     0     0    - /sys/fs/cgroup/net_cls,net_prio
cgroup             0     0     0    - /sys/fs/cgroup/rdma
cgroup             0     0     0    - /sys/fs/cgroup/memory
cgroup             0     0     0    - /sys/fs/cgroup/pids
cgroup             0     0     0    - /sys/fs/cgroup/cpuset
cgroup             0     0     0    - /sys/fs/cgroup/blkio
cgroup             0     0     0    - /sys/fs/cgroup/devices
systemd-1          -     -     -    - /proc/sys/fs/binfmt_misc
debugfs            0     0     0    - /sys/kernel/debug
hugetlbfs          0     0     0    - /dev/hugepages
mqueue             0     0     0    - /dev/mqueue
tmpfs           1.6G     0  1.6G   0% /run/user/1000
binfmt_misc        0     0     0    - /proc/sys/fs/binfmt_misc
tmpfs           1.6G     0  1.6G   0% /run/user/1002
        PHP Version: php-7.2.25
        PHP compile parameter: --prefix=/usr/local/php     --with-apxs2=/usr/local/apache/bin/apxs     --with-config-file-path=/usr/local/php/etc     --with-config-file-scan-dir=/usr/local/php/php.d     --with-pcre-dir=/usr/local/pcre     --with-imap     --with-kerberos     --with-imap-ssl     --with-libxml-dir     --with-openssl     --with-snmp     --with-libdir=lib64     --enable-mysqlnd --with-mysqli=mysqlnd --with-mysql-sock=/tmp/mysql.sock --with-pdo-mysql=mysqlnd     --with-gd --with-webp-dir --with-jpeg-dir --with-png-dir --with-xpm-dir --with-freetype-dir     --with-zlib     --with-bz2     --with-curl=/usr     --with-gettext     --with-gmp     --with-mhash     --with-icu-dir=/usr     --with-ldap     --with-ldap-sasl     --with-libmbfl     --with-onig     --with-unixODBC     --with-pspell=/usr     --with-enchant=/usr     --with-readline     --with-tidy=/usr     --with-xmlrpc     --with-xsl     --without-pear     --enable-zend-test     --enable-bcmath     --enable-calendar     --enable-dba     --enable-exif     --enable-ftp     --enable-gd-jis-conv     --enable-intl     --enable-mbstring     --enable-pcntl     --enable-shmop     --enable-soap     --enable-sockets     --enable-wddx     --enable-zip     
        Issue:failed to install php-7.2.25

**Comment by kreexus** [comment]
Эх, такая же проблема, но на Armbian ((

**Comment by neploho** [comment]
> Эх, такая же проблема, но на Armbian ((

На Debian 9 ставится без проблем.

**Comment by kreexus** [comment]
> На Debian 9 ставится без проблем.

Я думаю, что проблема в компиляции связана со скудностью репозитория armbian по сравнению с debian\ubuntu. На последних тоже встало отлично. На выходные если удастся, поковыряюсь с компиляцией php на armbian. Всё бы ничего, но если ставить php отдельно от LAMP через apt-get, то LAMP не видит никакого PHP...

**Comment by NetLancer** [comment]
So how about debian 10 today, eventually compatible..?

**Comment by l4ckyguy** [comment]
sed -i 's+-icu-+-xpm-+g' include/php.sh && sed -i 's+ --with-freetype-dir++g' include/php.sh

**Comment by neploho** [comment]
> So how about debian 10 today, eventually compatible..?

no

**Comment by l4ckyguy** [comment]
> > So how about debian 10 today, eventually compatible..?
> 
> no

YES =) do as i say
