### ISSUE TITLE
Can you add adminer for MySQL management?

### ISSUE THREAD

**Issue by nuriakman** [teddysun/lamp#157]
Hi,

[Adminer](https://www.adminer.org/) is a full-featured database management tool written in PHP.

I'll be happy to see this tool in your useful LAMP

**Comment by teddysun** [comment]
Done.
enjoy it please.

**Comment by nuriakman** [comment]
Thank you :)

If you interest: 

[https://www.adminer.org/latest.php](https://www.adminer.org/latest.php) is latest version for adminer all time.

You can see this info from here: [https://www.adminer.org/#download](https://www.adminer.org/#download)
