### ISSUE TITLE
redis 和 swoole不能同时安装

### ISSUE THREAD

**Issue by Liangkk** [teddysun/lamp#17]
你好,我在执行安装的时候,明确了同时安装redis和swoole,但是最后只有swool成功安装了...

**Comment by teddysun** [comment]
请提供安装日志以便分析原因

**Comment by Liangkk** [comment]
谢谢回复...以下是安装日志
[lampLog.txt](https://github.com/teddysun/lamp/files/870113/lampLog.txt)
