### ISSUE TITLE
阿里云centos8使用一键脚本安装python报错

### ISSUE THREAD

**Issue by BTFKM** [teddysun/lamp#170]
+------------------+
|  ERROR DETECTED  |
+------------------+
Installation package python failed.
The Full Log is available at /root/download/lamp/lamp.log
Please visit website: https://lamp.sh/faq.html for help
ed Hat 8.3.1-4) (GCC)) #1 SMP Wed Feb 5 02:00:39 UTC 2020
        Memery:
                      total        used        free      shared  buff/cache   available
Mem:           1829         186         917           0         725        1479
Swap:             0           0           0
        Disk:
        Filesystem      Size  Used Avail Use% Mounted on
sysfs              0     0     0    - /sys
proc               0     0     0    - /proc
devtmpfs        900M     0  900M   0% /dev
securityfs         0     0     0    - /sys/kernel/security
tmpfs           915M     0  915M   0% /dev/shm
devpts             0     0     0    - /dev/pts
tmpfs           915M  452K  915M   1% /run
tmpfs           915M     0  915M   0% /sys/fs/cgroup
cgroup             0     0     0    - /sys/fs/cgroup/systemd
pstore             0     0     0    - /sys/fs/pstore
bpf                0     0     0    - /sys/fs/bpf
cgroup             0     0     0    - /sys/fs/cgroup/cpu,cpuacct
cgroup             0     0     0    - /sys/fs/cgroup/rdma
cgroup             0     0     0    - /sys/fs/cgroup/pids
cgroup             0     0     0    - /sys/fs/cgroup/net_cls,net_prio
cgroup             0     0     0    - /sys/fs/cgroup/hugetlb
cgroup             0     0     0    - /sys/fs/cgroup/freezer
cgroup             0     0     0    - /sys/fs/cgroup/cpuset
cgroup             0     0     0    - /sys/fs/cgroup/memory
cgroup             0     0     0    - /sys/fs/cgroup/devices
cgroup             0     0     0    - /sys/fs/cgroup/blkio
cgroup             0     0     0    - /sys/fs/cgroup/perf_event
configfs           0     0     0    - /sys/kernel/config
/dev/vda1        40G  2.8G   38G   7% /
systemd-1          -     -     -    - /proc/sys/fs/binfmt_misc
mqueue             0     0     0    - /dev/mqueue
debugfs            0     0     0    - /sys/kernel/debug
hugetlbfs          0     0     0    - /dev/hugepages
tmpfs           183M     0  183M   0% /run/user/0
tracefs            0     0     0    - /sys/kernel/debug/tracing
binfmt_misc        0     0     0    - /proc/sys/fs/binfmt_misc
        Issue:failed to install python

**Comment by BTFKM** [comment]
没注意不支持centos8 改成7安装顺利

**Comment by teddysun** [comment]
我这不是前后脚嘛。
刚刚已经更新了，现在支持 CentOS 8 了

**Comment by BTFKM** [comment]
大佬我这块不太懂 但是我感觉好像把user/bin/icu-config脚本写成&nbsp;yes/bin/icu-config了
报错原文如下:
checking if iconv supports //IGNORE... no
checking if your cpp allows macro usage in include lines... yes
checking for IMAP support... yes
checking for IMAP Kerberos support... yes
checking for IMAP SSL support... yes
checking for utf8_mime2text signature... new
checking for U8T_DECOMPOSE... yes
checking for pam_start in -lpam... yes
checking for crypt in -lcrypt... yes
checking whether rfc822_output_address_list function present... yes
checking whether build with IMAP works... yes
checking for Firebird support... no
checking whether to enable internationalization support... yes
checking for location of ICU headers and libraries... not found
configure: error: Unable to detect ICU prefix or yes/bin/icu-config failed. Please verify ICU install prefix and make sure icu-config works.


+------------------+
|&nbsp; ERROR DETECTED&nbsp; |
+------------------+
Installation php-7.2.32 failed.
The Full Log is available at /root/lamp/lamp.log
Please visit website: https://lamp.sh/faq.html for help






[root@BTFKM1 lamp]# yum install libicu
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Package libicu-50.2-4.el7_7.x86_64 already installed and latest version
Nothing to do
[root@BTFKM1 lamp]# icu
bash: icu: command not found
[root@BTFKM1 lamp]# libicu
bash: libicu: command not found
[root@BTFKM1 lamp]# yum -y install libicu-devel
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Package libicu-devel-50.2-4.el7_7.x86_64 already installed and latest version
Nothing to do






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "teddysun/lamp"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月26日(星期天) 下午3:41
收件人:&nbsp;"teddysun/lamp"<lamp@noreply.github.com&gt;;
抄送:&nbsp;"BTFKM"<zyqcodmail@vip.qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [teddysun/lamp] 阿里云centos8使用一键脚本安装python报错 (#170)





 
我这不是前后脚嘛。
 刚刚已经更新了，现在支持 CentOS 8 了

**Comment by teddysun** [comment]
CentOS 7 下编译 PHP7.2 怎么会出这种错？不科学。
`configure: error: Unable to detect ICU prefix or yes/bin/icu-config failed. Please verify ICU install prefix and make sure icu-config works.`

请把完整日志 `/root/lamp/lamp.log` 通过邮件发给我看看。

**Comment by BTFKM** [comment]
邮件已发送 多谢

**Comment by BTFKM** [comment]
还有一个问题不过我解决了 就是在安装libzip的时候需要安装cmake3 脚本确实也下载cmake3了  
不过脚本在编译的时候似乎用的是cmake2.*
我自己先手动cmake编译了一下 编译不通过(提示cmake版本太低)  
再次手动cmake3后可以正常编译 脚本再运行没报错

**Comment by teddysun** [comment]
感谢反馈！
你说的 cmake 问题已经修正。

**Comment by teddysun** [comment]
> CentOS 7 下编译 PHP7.2 怎么会出这种错？不科学。
> `configure: error: Unable to detect ICU prefix or yes/bin/icu-config failed. Please verify ICU install prefix and make sure icu-config works.`
> 
> 请把完整日志 `/root/lamp/lamp.log` 通过邮件发给我看看。

已解决。
请重试一下即可。

**Comment by BTFKM** [comment]
谢谢
