### ISSUE TITLE
Problems making installations in Amazon EC2 instances

### ISSUE THREAD

**Issue by virtualorbis** [teddysun/lamp#171]
Hello,
I recently tried to install your LAMP framework in both CentOS and Ubuntu instances of AWS but in both cases I got this error message
configure: error: Unable to detect ICU prefix or yes/bin/icu-config failed. Please verify ICU install prefix and make sure icu-config works.

**Comment by teddysun** [comment]
Please attache full log `/root/lamp/lamp.log` at here or send to my email: i@teddysun.com

**Comment by teddysun** [comment]
Fixed it.
Please retry it.
