### ISSUE TITLE
CentOS7 中安装脚本报错

### ISSUE THREAD

**Issue by Jonathon52306** [teddysun/lamp#173]
![image](https://user-images.githubusercontent.com/46887506/88552257-77915700-d056-11ea-87eb-4269953801eb.png)

**Comment by Jonathon52306** [comment]
![image](https://user-images.githubusercontent.com/46887506/88552365-97c11600-d056-11ea-9d16-9f4de421298c.png)

**Comment by Jonathon52306** [comment]
![image](https://user-images.githubusercontent.com/46887506/88552430-aa3b4f80-d056-11ea-9ce3-815124e9f872.png)

**Comment by teddysun** [comment]
README 已经更新。请参考后，重试一下即可。
