### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by somebuddy87** [teddysun/lamp#174]
By executing lamp.sh i get the folowing Error:

`lamp.sh: 38: Syntax error: "(" unexpected (expecting "}")`

**Comment by teddysun** [comment]
出现这个问题是有可能因为你的系统不被支持导致的。
This problem may occur because your system is not supported. 

支持的系统列表如下：https://github.com/teddysun/lamp#supported-system
The list of supported systems is below: https://github.com/teddysun/lamp#supported-system

**Comment by somebuddy87** [comment]
I use Ubuntu-20.x

**Comment by teddysun** [comment]
DO NOT USE LIKE THIS:
```
sh lamp.sh 
lamp.sh: 38: Syntax error: "(" unexpected (expecting "}")
```
sh is NOT bash.

Just do like this:
```
./lamp.sh
```

**Comment by somebuddy87** [comment]
Thank you!
