### ISSUE TITLE
Installation php-7.3.21 failed

### ISSUE THREAD

**Issue by somebuddy87** [teddysun/lamp#175]
last part of my logfile:

/bin/bash /home/hnw/lamp/software/php-7.3.21/libtool --silent --preserve-dup-deps --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -Imain/ -I/home/hnw/lamp/software/php-7.3.21/main/ -DPHP_A>
/bin/bash /home/hnw/lamp/software/php-7.3.21/libtool --silent --preserve-dup-deps --mode=link cc -I/usr/include -g -O2 -fvisibility=hidden -pthread -DZTS -DZEND_SIGNALS   -rpath /home/hnw/lamp/s>
/bin/ld: cannot find -liconv
collect2: error: ld returned 1 exit status
make: *** [Makefile:164: libphp7.la] Error 1

+------------------+
|  ERROR DETECTED  |
+------------------+
Installation php-7.3.21 failed.
The Full Log is available at /home/hnw/lamp/lamp.log
Please visit website: https://lamp.sh/faq.html for help
2)) #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020
        Memery:
                      total        used        free      shared  buff/cache   available
Mem:           1973         205         766           0        1001        1576
Swap:          2047           1        2046
        Disk:
        Filesystem                         Size  Used Avail Use% Mounted on
sysfs                                 0     0     0    - /sys
proc                                  0     0     0    - /proc
udev                               945M     0  945M   0% /dev
devpts                                0     0     0    - /dev/pts
tmpfs                              198M  1.1M  197M   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv   20G  7.5G   12G  41% /
securityfs                            0     0     0    - /sys/kernel/security
tmpfs                              987M     0  987M   0% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
tmpfs                              987M     0  987M   0% /sys/fs/cgroup
cgroup2                               0     0     0    - /sys/fs/cgroup/unified
cgroup                                0     0     0    - /sys/fs/cgroup/systemd
pstore                                0     0     0    - /sys/fs/pstore
none                                  0     0     0    - /sys/fs/bpf
cgroup                                0     0     0    - /sys/fs/cgroup/rdma
cgroup                                0     0     0    - /sys/fs/cgroup/blkio
cgroup                                0     0     0    - /sys/fs/cgroup/pids
cgroup                                0     0     0    - /sys/fs/cgroup/cpuset
cgroup                                0     0     0    - /sys/fs/cgroup/cpu,cpuacct
cgroup                                0     0     0    - /sys/fs/cgroup/net_cls,net_prio
cgroup                                0     0     0    - /sys/fs/cgroup/memory
cgroup                                0     0     0    - /sys/fs/cgroup/freezer
cgroup                                0     0     0    - /sys/fs/cgroup/hugetlb
cgroup                                0     0     0    - /sys/fs/cgroup/devices
cgroup                                0     0     0    - /sys/fs/cgroup/perf_event
systemd-1                             -     -     -    - /proc/sys/fs/binfmt_misc
hugetlbfs                             0     0     0    - /dev/hugepages
mqueue                                0     0     0    - /dev/mqueue
debugfs                               0     0     0    - /sys/kernel/debug
tracefs                               0     0     0    - /sys/kernel/tracing

**Comment by teddysun** [comment]
Thank you for your report. 
It just been fixed.
Please retry it.

**Comment by somebuddy87** [comment]
i just pulled the newest git and try it again.
same Error: 

/bin/ld: cannot find -liconv

**Comment by teddysun** [comment]
It can be fixed and tested in Ubuntu 20.04
Maybe you can reinstall in fresh Ubuntu 20.04 or uninstall it at first.

**Comment by somebuddy87** [comment]
After deleting /usr/local/libiconv the installation succeeded!
Thank you!
