### ISSUE TITLE
建议安装完成后，不要自动删除 software  文件夹里的东西

### ISSUE THREAD

**Issue by li914** [teddysun/lamp#176]
建议安装完成后，不要自动删除 software  文件夹里的东西

**Comment by teddysun** [comment]
成功安装后，如果不删除会占用很大的硬盘空间。
而且也没有留着的必要。

**Comment by li914** [comment]
在这里很感谢您，这个脚本，很方便配置。

这个文件夹里的软件以及依赖，下载一次需要好几个小时，不容易。
只是建议，将自动改为提示，让输入是否删除
