### ISSUE TITLE
LetsEncrypt Option Fails

### ISSUE THREAD

**Issue by GarethWright** [teddysun/lamp#177]
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'python-is-python2' instead of 'python'
Note, selecting 'python-dev-is-python2' instead of 'python-dev'
Package python-virtualenv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-virtualenv' has no installation candidate
Error: Create Let's Encrypt SSL Certificate failed

**Comment by teddysun** [comment]
See https://github.com/certbot/certbot/issues/8021

**Comment by teddysun** [comment]
Run the following commands below:
```
apt-get update
apt-get install python3-virtualenv
```

and retry it.

Reference URL: 
https://techdirectarchive.com/2020/06/30/the-package-python-virtualenv-has-no-installation-candidate-error/
