### ISSUE TITLE
Installation php-5.6.40 failed. Debian 10

### ISSUE THREAD

**Issue by kazuma777** [teddysun/lamp#179]
+------------------+
|  ERROR DETECTED  |
+------------------+
Installation php-5.6.40 failed.
The Full Log is available at /root/lamp/lamp.log
Please visit website: https://lamp.sh/faq.html for help
root@vultr:~/lamp#

[lamp.log](https://github.com/teddysun/lamp/files/5145206/lamp.log)

**Comment by teddysun** [comment]
Because openssl is latest version in Debian 10 when building PHP 5.6.40.
Please choose Debian 8 If you have to install PHP 5.6

**Comment by kazuma777** [comment]
> Because openssl is latest version in Debian 10 when building PHP 5.6.40.
> Please choose Debian 8 If you have to install PHP 5.6

If I choose ubuntu 18 server? will working?

**Comment by teddysun** [comment]
> If I choose ubuntu 18 server? will working?

It is better to choose ubuntu 16.04
