### ISSUE TITLE
web on virtual host, fail to write or upload data

### ISSUE THREAD

**Issue by zettotry** [teddysun/lamp#180]
how to make the website on the virtual host work properly? my website cannot upload data to save files or articles.
i don't know the chown command or chmod function.

**Comment by teddysun** [comment]
`chown -R apache.apache /data/www/yourwebsite`

**Comment by zettotry** [comment]
> 
> 
> `chown -R apache.apache /data/www/yourwebsite`

still can't sir. is there another way ?

**Comment by zettotry** [comment]
please anyone helpme

**Comment by zettotry** [comment]
> 
> 
> `chown -R apache.apache /data/www/yourwebsite`

please helpme sir , thats command not working.

**Comment by omgbox** [comment]
> > `chown -R apache.apache /data/www/yourwebsite`
> 
> please helpme sir , thats command not working.

> sudo chown www-data:www-data -R /data/www/uploads
