### ISSUE TITLE
Error on CentOS 8 - libsodium

### ISSUE THREAD

**Issue by brinsleyparagao** [teddysun/lamp#181]
2020-09-22 03:29:16 (840 KB/s) - ‘libsodium-2.0.22.tar.gz’ saved [28531/28531]

libsodium-2.0.22.tar.gz download completed...
tar (child): libsodium-2.0.22.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
/lamp/include/php-modules.sh: line 649: cd: libsodium-2.0.22: No such file or directory
Cannot find config.m4. 
Make sure that you run '/usr/local/php/bin/phpize' in the top level source directory of the module

**Comment by teddysun** [comment]
Thanks for your report.
Fixed it.
