### ISSUE TITLE
Centos 8 Stream安装失败

### ISSUE THREAD

**Issue by liwemhao** [teddysun/lamp#182]
因为手动解决了问题，原先的日志被覆盖了
------------------------- Install Overview --------------------------

Apache: httpd-2.4.46
Apache Location: /usr/local/apache
Apache Additional Modules:
mod_wsgi-4.7.1
modsecurity-2.9.3
tomcat-connectors-1.2.48-src

Database: mariadb-10.5.6
MariaDB Location: /usr/local/mariadb
MariaDB Data Location: /usr/local/mariadb/data
MariaDB Root Password: xxxxxxxx

Database Management Modules:
phpMyAdmin-5.0.3-all-languages

PHP: php-7.4.11
PHP Location: /usr/local/php
PHP Additional Extensions:
ioncube_loaders
apcu-5.1.18
imagick-3.4.4
redis-5.3.1
libsodium-2.0.22

KodExplorer: do_not_install

提示lynx安装失败，谷歌发现在Centos 8里，lynx在CentOS-Stream-PowerTools.repo里面，该源默认未启用

**Comment by teddysun** [comment]
PowerTools 默认是被开启的，详见：
https://github.com/teddysun/lamp/blob/master/include/public.sh#L1009

**Comment by liwemhao** [comment]
呃，可能stream跟一般的有点区别吧
