### ISSUE TITLE
WSL 2 Custom domain seems not working

### ISSUE THREAD

**Issue by huraji** [teddysun/lamp#185]
Hello there,

custom domain like example.test set in `/etc/hosts` and `/Windows/System32/drivers/etc/hosts` seems not working. Added as following:

```
127.0.0.1    example.test
::1          example.test
```

Also httpd service restarted.
Any idea?

**Comment by huraji** [comment]
Just fixed as following:

```
127.0.0.1    example.test
::1          example.test localhost
```

I guess it's something regarding the wsl2 DNS resolution. Appending localhost after the custom domain fixed my issue. Maybe to mention in the documentation. (See https://github.com/microsoft/WSL/issues/5728)

**Comment by sntxerror** [comment]
works for me! thanks

**Comment by ZoeZhong-AAXIS** [comment]
works for me! Thanks.
