### ISSUE TITLE
Let's Encrypt SSL issue

### ISSUE THREAD

**Issue by brinsleyparagao** [teddysun/lamp#189]
In debian 10 today [17-12-20202] i give this error

```
Starting create Let's Encrypt SSL Certificate...
Skipping bootstrap because certbot-auto is deprecated on this system.
Your system is not supported by certbot-auto anymore.
Certbot cannot be installed.
Please visit https://certbot.eff.org/ to check for other alternatives.
Error: Create Let's Encrypt SSL Certificate failed
```

**Comment by buzz3rs** [comment]
I'm getting this on Ubuntu 16 & 18 as well, I had to manually download the latest version and replace the old certbot to fix it

**Comment by teddysun** [comment]
https://community.letsencrypt.org/t/certbot-auto-no-longer-works-on-debian-based-systems/139702/7
