### ISSUE TITLE
Crontab in PHP fail

### ISSUE THREAD

**Issue by brinsleyparagao** [teddysun/lamp#191]
hello...

How to set config to execute this crontab?

`php -q /data/www/brinsley/crons/cron.php`

I try put this line in crontab, but donw execute fine.

**Comment by iFastVPN** [comment]
Hey mate, try this  

5 * * * * /usr/bin/php -q /data/www/brinsley/crons/cron.php


Then restart your crontab
Ubuntu 
sudo systemctl restart crond.service

Centos
sudo service cron restart
