### ISSUE TITLE
php扩展 "topthink/think-annotation": "^v1.1.3" 不能用

### ISSUE THREAD

**Issue by ljsenjj** [teddysun/lamp#198]
你好，我在CentOS-8.3.2011-x86_64-dvd1.iso最小安装下
用lamp.sh安装了LAMP环境，安装了下面的模块

Apache Additional Modules:
mod_wsgi-4.7.1
modsecurity-2.9.3
tomcat-connectors-1.2.48-src

Database: mysql-5.7.32
MySQL Location: /usr/local/mysql
MySQL Data Location: /usr/local/mysql/data

PHP: php-7.4.16
PHP Location: /usr/local/php
PHP Additional Extensions:
redis-5.3.2
xdebug-2.9.8

---------------------------------------------------------------------

然后我用，composer create-project topthink/think tp6，新建了thinkphp工程
加入了"topthink/think-annotation": "^v1.1.3" 扩展，并定义好注解路由，但是php找不到路由
我在另外的不是用lamp.sh安装的php环境中，同样的代码是可以用think-annotation的
所有我想问下，lamp.sh在安装php的时候没有做了关于路由的设置？感谢

**Comment by teddysun** [comment]
> lamp.sh在安装php的时候没有做了关于路由的设置？

没有这方面的设置。
