### ISSUE TITLE
Installation ImageMagick-7.0.11-12 failed.

### ISSUE THREAD

**Issue by cnyue1** [teddysun/lamp#199]
an error:Installation ImageMagick-7.0.11-12 failed.
how can i deal with it
[lamp.log](https://github.com/teddysun/lamp/files/6528131/lamp.log)

**Comment by teddysun** [comment]
```
CCLD     utilities/magick
MagickCore/.libs/libMagickCore-7.Q16HDRI.so: undefined reference to `WebPMemoryWriterClear'
collect2: error: ld returned 1 exit status
make[1]: *** [utilities/magick] Error 1
make[1]: Leaving directory `/usr/local/src/ImageMagick-7.0.11-12'
make: *** [all] Error 2
```
the same error occurred.
please upgrade to latest script & use ImageMagick-7.0.11-13 to retry it.
it already been fixed by https://github.com/teddysun/lamp/commit/c7d378234a0ab4fc1086b2dfdcdc3de7f30d0c97
