### ISSUE TITLE
install new php-ext

### ISSUE THREAD

**Issue by ducna96** [teddysun/lamp#201]
How to install new php ext from lamp script ? 
thanks

**Comment by teddysun** [comment]
if the PHP ext in LAMP script, just rerun `lamp.sh` and choose same option( Apache, MySQL, PHP version etc).
and choose what you want to install ext when choose PHP ext.

if the PHP ext is not in LAMP script, can not auto install PHP ext by script.
You can manually install it.

**Comment by ducna96** [comment]
how to manually install it, bcs version php can match with version if i use apt install. please help ...

**Comment by ducna96** [comment]
i use command mv /usr/local/php /usr/local/php.bak, and i reinstall with apt install php7.4 ,
but , apache still take old php version in /usr/local/php
![image](https://user-images.githubusercontent.com/35019158/123567504-81828380-d7ec-11eb-9c9f-e620f9dd8bd7.png)
please help me.
