### ISSUE TITLE
只能说是一个奇怪的现象，但也许是一个bug。

### ISSUE THREAD

**Issue by Skyepose** [teddysun/lamp#21]
安装完毕LAMP后，架设了一个Wordpress，我想用奇云测来测试这个网站到中国的速度，但是将网址输入奇云测开始测试后发现，随着测试的开始，主机的内存被Httpd和mysql疯狂占据，随着测试的结束，主机就当机了。我在思索是不是奇云测强奸了我的网站。但是使用军哥的LNMP架设的网站就这个问题。测试主机环境为：
Digitalocean还有Hostker云主机。
奇云测地址为：http://ce.cloud.360.cn
<img width="1440" alt="screen shot 2017-05-22 at 7 41 20 pm" src="https://cloud.githubusercontent.com/assets/9482245/26351614/9b07248a-3fb8-11e7-9d3f-6faf43a074bf.png">

<img width="1440" alt="screen shot 2017-05-22 at 7 41 30 pm" src="https://cloud.githubusercontent.com/assets/9482245/26351590/8988bb2e-3fb8-11e7-8f7f-9bdadd1e69bc.png">

**Comment by Teddysun** [comment]
压力测试时会产生大量连接（并发），网站如果没有做静态化的话，会有大量的 MySQL 查询。
最后 MySQL 耗光系统内存，挂掉。
