### ISSUE TITLE
libenchant-dev install failed on Debian 11

### ISSUE THREAD

**Issue by bolucat** [teddysun/lamp#221]
This is only a suggestion for this script to support next stable version of Debian

On Debian 11 package **`libenchant-dev`** does not exist when install PHP (using standard official sources):

https://github.com/teddysun/lamp/blob/6f12b028483f101819b1a70187cfc6be57c3e786/include/php-modules.sh#L131

This package should be replaced by **`libenchant-2-dev`** , and after replacing this package everything works fine

**Comment by teddysun** [comment]
Not support Debian 11 yet.
This project now only fixes bugs.

**Comment by bolucat** [comment]
I got it, I will close this issue and if anyone confronts the same problem can find a solution here
