### ISSUE TITLE
lamp一键安装脚本在debian8.6下更新openssl 的问题

### ISSUE THREAD

**Issue by wlfcss** [teddysun/lamp#23]
2017 年 05 月 27 日的版本，貌似加入了更新openssl为1.02l的功能，但它并不能成功卸载原有的openssl，导致我服务器上出现了两个openssl（我的推测），以至于我自行安装特定版本swoole时失败。
`root@xxx:~/swoole-src-1.9.14# openssl version
openssl: /usr/local/lib/libssl.so.1.0.0: no version information available (required by openssl)
openssl: /usr/local/lib/libssl.so.1.0.0: no version information available (required by openssl)
openssl: /usr/local/lib/libssl.so.1.0.0: no version information available (required by openssl)
openssl: /usr/local/lib/libcrypto.so.1.0.0: no version information available (required by openssl)
openssl: /usr/local/lib/libcrypto.so.1.0.0: no version information available (required by openssl)
openssl: /usr/local/lib/libcrypto.so.1.0.0: no version information available (required by openssl)
openssl: /usr/local/lib/libcrypto.so.1.0.0: no version information available (required by openssl)
OpenSSL 1.0.2k  26 Jan 2017 (Library: OpenSSL 1.0.2l  25 May 2017)`

` cc -I. -I/root/swoole-src-1.9.14 -DPHP_ATOM_INC -I/root/swoole-src-1.9.14/include -I/root/swoole-src-1.9.14/main -I/root/swoole-src-1.9.14 -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/root/swoole-src-1.9.14 -I/root/swoole-src-1.9.14/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /root/swoole-src-1.9.14/swoole.c  -fPIC -DPIC -o .libs/swoole.o
In file included from /root/swoole-src-1.9.14/swoole.c:16:0:
/root/swoole-src-1.9.14/php_swoole.h:123:2: error: #error "Enable openssl support, require openssl library."
 #error "Enable openssl support, require openssl library."
  ^
Makefile:194: recipe for target 'swoole.lo' failed
make: *** [swoole.lo] Error 1
`

**Comment by Showfom** [comment]
使用 jessie-backports 升级一下
