### ISSUE TITLE
issue with deprecated link in /include/config.sh

### ISSUE THREAD

**Issue by comsyspro** [teddysun/lamp#231]
In /include/config.sh there is an error with a deprecated link which doesn't exist anymore and gives a timeout error running ./lamp.sh:

pcre_filename="pcre-8.44"
pcre_filename_url="https://ftp.pcre.org/pub/pcre/pcre-8.44.tar.gz"

The link should be instead:
https://ftp.exim.org/pub/pcre/pcre-8.44.tar.gz

There is also a newer version:
https://ftp.exim.org/pub/pcre/pcre-8.45.tar.gz

**Comment by teddysun** [comment]
Thank you!
It has been fixed.
