### ISSUE TITLE
Installation mcrypt-2.6.8 failed

### ISSUE THREAD

**Issue by soniczyz** [teddysun/lamp#247]
Installation interrupted with message shown below: 

checking whether mhash >= 0.8.15... no
configure: error: "You need at least libmhash 0.8.15 to compile this program. http://mhash.sf.net/"

+------------------+
|  ERROR DETECTED  |
+------------------+
Installation mcrypt-2.6.8 failed.
The Full Log is available at /root/lamp/lamp.log
Please visit website: https://lamp.sh/faq.html for help
20150623 (Red Hat 4.8.5-39) (GCC) ) #1 SMP Sun Jul 26 15:27:06 UTC 2020
        Memery:
                      total        used        free      shared  buff/cache   available
Mem:           3789         128         587          40        3073        3338
Swap:             0           0           0
        Disk:
        Filesystem      Size  Used Avail Use% Mounted on
sysfs              0     0     0    - /sys
proc               0     0     0    - /proc
devtmpfs        1.9G     0  1.9G   0% /dev
securityfs         0     0     0    - /sys/kernel/security
tmpfs           1.9G     0  1.9G   0% /dev/shm
devpts             0     0     0    - /dev/pts
tmpfs           1.9G   41M  1.9G   3% /run
tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
cgroup             0     0     0    - /sys/fs/cgroup/systemd
pstore             0     0     0    - /sys/fs/pstore
cgroup             0     0     0    - /sys/fs/cgroup/perf_event
cgroup             0     0     0    - /sys/fs/cgroup/cpuset
cgroup             0     0     0    - /sys/fs/cgroup/pids
cgroup             0     0     0    - /sys/fs/cgroup/hugetlb
cgroup             0     0     0    - /sys/fs/cgroup/devices
cgroup             0     0     0    - /sys/fs/cgroup/net_cls,net_prio
cgroup             0     0     0    - /sys/fs/cgroup/cpu,cpuacct
cgroup             0     0     0    - /sys/fs/cgroup/freezer
cgroup             0     0     0    - /sys/fs/cgroup/memory
cgroup             0     0     0    - /sys/fs/cgroup/blkio
configfs           0     0     0    - /sys/kernel/config
/dev/vda1        79G   38G   38G  51% /
systemd-1          -     -     -    - /proc/sys/fs/binfmt_misc
debugfs            0     0     0    - /sys/kernel/debug
mqueue             0     0     0    - /dev/mqueue
hugetlbfs          0     0     0    - /dev/hugepages
binfmt_misc        0     0     0    - /proc/sys/fs/binfmt_misc
tmpfs           379M     0  379M   0% /run/user/0
        PHP Version: php-8.0.25
        PHP compile parameter: 
    --prefix=/usr/local/php     --with-apxs2=/usr/local/apache/bin/apxs     --with-config-file-path=/usr/local/php/etc     --with-config-file-scan-dir=/usr/local/php/php.d     --with-pcre-jit     --with-imap     --with-kerberos     --with-imap-ssl     --with-openssl     --with-snmp     --with-libdir=lib64     --enable-mysqlnd     --with-mysqli=mysqlnd     --with-mysql-sock=/tmp/mysql.sock     --with-pdo-mysql=mysqlnd     --enable-gd     --with-webp     --with-jpeg     --with-xpm     --with-freetype     --with-zlib     --with-bz2     --with-curl=/usr     --with-gettext     --with-gmp     --with-mhash     --with-ldap     --with-ldap-sasl     --with-pspell=/usr     --with-enchant=/usr     --with-readline     --with-tidy=/usr     --with-xsl     --with-password-argon2     --enable-zend-test     --enable-bcmath     --enable-calendar     --enable-dba     --enable-exif     --enable-ftp     --enable-gd-jis-conv     --enable-intl     --enable-mbstring     --enable-pcntl     --enable-shmop     --enable-soap     --enable-sockets     --with-zip     
        Issue:failed to install mcrypt-2.6.8

**Comment by teddysun** [comment]
Thanks!
Fixed it. Please try again.
