### ISSUE TITLE
怎么安装php5.3和5.6?

### ISSUE THREAD

**Issue by piiiiiiiiiiiiiii** [teddysun/lamp#259]
系统是centos7，一些老程序只能跑在php老版本，怎样安装php5.3和5.6?

**Comment by piiiiiiiiiiiiiii** [comment]
Q10：程序只能支持到PHP 5.3，不支持PHP 5.4，请问具体如何降级到PHP 5.3呢？是否可以直接卸载 PHP 然后单独重新安装PHP 5.3 ？

可以是可以，不过比较麻烦，你要自己重新编译 PHP 5.3.29。
删除已有的 PHP 步骤：
rm -rf /etc/php.ini /usr/bin/php* /usr/local/php
编译 PHP 5.3.29 有几点需要注意的。你需要把环境里的 Apache， MySQL 或 MariaDB 配置一并 configure 好才行。
当然还有一种办法就是备份好数据，卸载 LAMP 后再次安装时选择 PHP 5.3 版本即可。


------------------------------

安装时最低都是php7啊老板

**Comment by teddysun** [comment]
php5.3 和 5.6 太古老了，只能在旧系统里安装，比如 CentOS 6
脚本早已不支持。

**Comment by piiiiiiiiiiiiiii** [comment]
> php5.3 和 5.6 太古老了，只能在旧系统里安装，比如 CentOS 6 脚本早已不支持。

老板指条路，我得用啊

**Comment by piiiiiiiiiiiiiii** [comment]
老板指条路，我得用啊
