### ISSUE TITLE
脚本最后显示进程和端口的命令是什么?

### ISSUE THREAD

**Issue by piiiiiiiiiiiiiii** [teddysun/lamp#260]
脚本执行完合，最后面会有一个进程和端口的运行列表，试了一下不像是netstat -n或lsof的运行结果，请问下是哪个命令?

谢谢泰迪~

**Comment by teddysun** [comment]
`netstat -nxtulpe`

**Comment by piiiiiiiiiiiiiii** [comment]
> `netstat -nxtulpe`

666
