### ISSUE TITLE
Failed to download mysql-8.0.38

### ISSUE THREAD

**Issue by sudanking** [teddysun/lamp#272]
When I try to install mysql 8.0.38 I get the below error:

Failed to download mysql-8.0.38-linux-glibc2.12-x86_64.tar.xz, please download it to /root/lamp/software directory manually and try again.

I think there is no more version 8.0.38

**Comment by sudanking** [comment]
I changed to config.sh and use 8.0.37 
it is working fine now
but I think you need to go for the latest version 8.4.0 in the next update

**Comment by teddysun** [comment]
It looks like MySQL official removed mysql-8.0.38 file.
And mysql-8.0.39 is the latest version now.
