### ISSUE TITLE
Install openssl failed

### ISSUE THREAD

**Issue by MagicBird220** [teddysun/lamp#274]
Installing openssl-1.1.1w...
openssl-1.1.1w.tar.gz [found]

gzip: stdin: unexpected end of file
tar: 归档文件中异常的 EOF
tar: 归档文件中异常的 EOF
tar: Error is not recoverable: exiting now
/root/lamp/include/public.sh:行435: ./config: 没有那个文件或目录

+------------------+
|  ERROR DETECTED  |
+------------------+
Installation openssl-1.1.1w failed.

This is the installation log, how to fix it ?

**Comment by teddysun** [comment]
It looks like openssl-1.1.1w.tar.gz download failed.
Delete openssl-1.1.1w.tar.gz (empty) file, and retry it
