### ISSUE TITLE
ubuntu 24.04 apt_list compatibility issues

### ISSUE THREAD

**Issue by ZiaChiu** [teddysun/lamp#277]
On Ubuntu 24.04, you will give error when you are install libncurses5,libncurses5-dev and libaio1.

because libncurses5 will not be supported (it has been changed to libncurses6 and libncurses-dev); libaio1 has been replaced by libaio1t64.

# solution(Testing):
In lamp/mysql.sh(65 line),  

from 
```
...
#Install Database common
common_install() {
    local apt_list=(libncurses5 libncurses5-dev cmake m4 bison libaio1 libaio-dev numactl)
         ...
}
```
change to 

```
...
common_install() {
     local apt_list=(libncurses6 libncurses-dev cmake m4 bison libaio1t64 libaio-dev numactl)
         ...
}

**Comment by mrg123** [comment]
环境: ubantu 24.04,  ARM64

**Comment by mrg123** [comment]
执行的时候变成安装: libncurses6-dev, 这个包没有了,最新包如下
