### ISSUE TITLE
ip直接访问问题

### ISSUE THREAD

**Issue by EzraZhao** [teddysun/lamp#35]
现在ip直接访问的话是lamp页面，我想配置成我项目的页面，该怎么使用呢

**Comment by teddysun** [comment]
在 /usr/local/apache/conf/vhost 下新建一个虚拟主机 conf 文件，举例：sample.conf
内容如下所示：
<virtualhost *:80>
ServerName  IP地址
Redirect 302 / https://yourdomain.com
</virtualhost>

也就是说，新建一个 ServerName 为公网 IP 的虚拟主机， 302 重定向到你的网站域名即可。
最后，重启 Apache 生效。

**Comment by Edelwiess** [comment]
还需要一行

</VirtualHost>
在末尾和
<VirtualVHost *:80>
对应上
