### ISSUE TITLE
tar: mysql-5.7.20-linux-glibc2.12-i686/support-files/mysql-log-rotate: Cannot open: No such file or directory

### ISSUE THREAD

**Issue by limang** [teddysun/lamp#36]
您好,我在centos中安装 mysql 报以上错误

**Comment by teddysun** [comment]
请提供具体安装日志。

**Comment by limang** [comment]
tar: mariadb-5.5.58-linux-i686/bin/mysql_client_test_embedded: Wrote only 8192 of 10240 bytes
tar: mariadb-5.5.58-linux-i686/include/mysql/mysql.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/mysql_com.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/mysql_time.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/ma_dyncol.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/my_list.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/my_alloc.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/typelib.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/my_dbug.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/m_string.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/my_sys.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/my_xml.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/mysql_embed.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/my_decimal_limits.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/my_pthread.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/decimal.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/errmsg.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/my_global.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/my_net.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/my_getopt.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/sslopt-longopts.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/my_dir.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/sslopt-vars.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/sslopt-case.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/my_valgrind.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/sql_common.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/keycache.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/m_ctype.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/my_attribute.h: Cannot open: No such file or directory
tar: mariadb-5.5.58-linux-i686/include/mysql/my_compiler.h:

**Comment by limang** [comment]
以上是从lamp.log

**Comment by limang** [comment]
以上是从lamp.log找到，我装了mysql-5.7 5.6 mariadb-5.5.58 都是类似的错误

**Comment by limang** [comment]
OS                   : CentOS 6.9
Arch                 : i686 (32 Bit)
Kernel               : 2.6.32-696.6.3.el6.i686

**Comment by teddysun** [comment]
请检查硬盘空间是否足够。

**Comment by limang** [comment]
多谢！
