### ISSUE TITLE
Mysql service exited!

### ISSUE THREAD

**Issue by reid3290** [teddysun/lamp#41]
I installed lamp and developed a wordpress based website. It all worked well at begin. But after several days(I don't know the exact time) my website was down and complained "Error make databse connection". I checked ```/etc/init.d/mysqld status```, it showed mysql service was **active(exited)**. I had to run ```/etc/init.d/mysqld restart``` to make it **active(running)**. And then my website worked again. This happed a lot of times.
So what dose cause this situation, how can I avoid it, or how can I make the mysql service restart automatically?
Thanks!

**Comment by rovertang** [comment]
me too
I can't find the reason.
so I create a cron job to check mysql status and if it die then restart it.
bash code list:

#!/bin/bash
pgrep -x mysqld &> /dev/null
if [ $? -ne 0 ]
then
echo “At time: `date` :MySQL is stop .”>> /data/checkmysql.log
/etc/init.d/mysqld start
else
echo “MySQL server is running .”
fi
