### ISSUE TITLE
xdebug安装失败

### ISSUE THREAD

**Issue by jiangjiucong** [teddysun/lamp#43]
[log.zip](https://github.com/teddysun/lamp/files/1583059/log.zip)
xdebug安装失败，安装日志在下面文件中

**Comment by teddysun** [comment]
checking Check for supported PHP versions... configure: error: not supported. Need a PHP version >= 5.5.0 and < 7.2.0 (found 7.2.0)X

原因是，Xdebug 目前还不支持 PHP 7.2
