### ISSUE TITLE
Debian 8 64添加SSL站点出错

### ISSUE THREAD

**Issue by mixool** [teddysun/lamp#47]
使用最新的脚本，域名已经解析到VPS了，错误如下：
root@KVM:~/lamp# lamp add
Please enter server names(example: www.lamp.sh lamp.sh): img.xxx.net
Please enter website root directory(default:/data/www/img.xxx.net): 
Please enter Administrator Email address: xxx@gmail.com
Administrator Email address:xxx@gmail.com
Do you want to create a database and mysql user with same name? [y/n]:n
Do not create a database
Virtual host [img.xxx.net] has been created
Website root directory is: /data/www/img.xxx.net
Reloading the apache config file...
Syntax OK
Reload success
Do you want to add a SSL certificate? [y/n]:y
1: Use your own SSL Certificate and Key
2: Use Let's Encrypt to create SSL Certificate and Key
Please enter 1 or 2: 2
You have already chosen Let's Encrypt
It will be processed automatically
Starting create Let's Encrypt SSL Certificate...
Bootstrapping dependencies for Debian-based OSes... (you can skip this with --no-bootstrap)
Ign http://ftp.us.debian.org jessie InRelease
Get:1 http://ftp.us.debian.org jessie-updates InRelease [145 kB]
Get:2 http://security.debian.org jessie/updates InRelease [63.1 kB]
Hit http://ftp.us.debian.org jessie Release.gpg                      
Hit http://ftp.us.debian.org jessie Release          
Get:3 http://security.debian.org jessie/updates/main Sources [208 kB]
Hit http://ftp.us.debian.org jessie-updates/main Sources                      
Get:4 http://ftp.us.debian.org jessie-updates/main amd64 Packages/DiffIndex [9,868 B]
Get:5 http://ftp.us.debian.org jessie-updates/main Translation-en/DiffIndex [3,688 B]
Hit http://ftp.us.debian.org jessie/main Sources
Hit http://ftp.us.debian.org jessie/main amd64 Packages                             
Get:6 http://security.debian.org jessie/updates/main amd64 Packages [480 kB]        
Hit http://ftp.us.debian.org jessie/main Translation-en                                     
Get:7 http://security.debian.org jessie/updates/main Translation-en [240 kB]                     
Fetched 1,150 kB in 4s (236 kB/s)                                                                
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
augeas-lenses is already the newest version.
libaugeas0 is already the newest version.
ca-certificates is already the newest version.
gcc is already the newest version.
libffi-dev is already the newest version.
libssl-dev is already the newest version.
openssl is already the newest version.
python is already the newest version.
python-dev is already the newest version.
python-virtualenv is already the newest version.
virtualenv is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 131 not upgraded.
WARNING: unable to check for updates.
Creating virtual environment...
Installing Python packages...
Traceback (most recent call last):
  File "/tmp/tmp.hJjRpwMxjX/pipstrap.py", line 165, in <module>
    exit(main())
  File "/tmp/tmp.hJjRpwMxjX/pipstrap.py", line 146, in main
    for url, digest in PACKAGES]
  File "/tmp/tmp.hJjRpwMxjX/pipstrap.py", line 121, in hashed_download
    response = opener().open(url)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/usr/lib64/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
Error: Create Let's Encrypt SSL Certificate failed!
Reloading the apache config file...
Syntax OK
Reload success
All done

完成后可以访问HTTP，但是不能访问HTTPS，自己找不到解决办法了.

**Comment by teddysun** [comment]
从错误信息来看，是环境的问题。
Installing Python packages...
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]

那么，你还可以参考以下网址：
https://teddysun.com/527.html
手动去申请证书后，再次执行 lamp add，选择
Use your own SSL Certificate and Key
安装证书即可。
