### ISSUE TITLE
Installation memcache-3.0.8 failed

### ISSUE THREAD

**Issue by stoneyun2018** [teddysun/lamp#50]
2018 年 02 月 14 日更新日志：
修正：PHP 扩展 memcached 安装失败的问题，但还是安装出错

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
/bin/sh /root/lamp-master/software/memcache-3.0.8/libtool --mode=compile cc -I/usr/local/php/include/php -I. -I/root/lamp-master/software/memcache-3.0.8 -DPHP_ATOM_INC -I/root/lamp-master/software/memcache-3.0.8/include -I/root/lamp-master/software/memcache-3.0.8/main -I/root/lamp-master/software/memcache-3.0.8 -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /root/lamp-master/software/memcache-3.0.8/memcache.c -o memcache.lo 
mkdir .libs
 cc -I/usr/local/php/include/php -I. -I/root/lamp-master/software/memcache-3.0.8 -DPHP_ATOM_INC -I/root/lamp-master/software/memcache-3.0.8/include -I/root/lamp-master/software/memcache-3.0.8/main -I/root/lamp-master/software/memcache-3.0.8 -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/lamp-master/software/memcache-3.0.8/memcache.c  -fPIC -DPIC -o .libs/memcache.o
In file included from /root/lamp-master/software/memcache-3.0.8/php_memcache.h:34:0,
                 from /root/lamp-master/software/memcache-3.0.8/memcache.c:30:
/root/lamp-master/software/memcache-3.0.8/memcache_pool.h:45:47: 致命错误：ext/standard/php_smart_str_public.h：没有那个文件或目录
 #include "ext/standard/php_smart_str_public.h"
                                               ^
编译中断。
make: *** [memcache.lo] 错误 1

+------------------+
|  ERROR DETECTED  |
+------------------+
Installation memcache-3.0.8 failed.
The Full Log is available at /root/lamp-master/lamp.log
Please visit website: https://lamp.sh/faq.html for help

**Comment by FlySelfLog** [comment]
参考issue #39，是memcache本身的问题，没有兼容php7

**Comment by stoneyun2018** [comment]
收到，谢谢
一键安装时，能否将memcache替换为memcached呢

**Comment by teddysun** [comment]
@FlySelfLog @stoneyun2018  Thank you！

PHP memcache 扩展已经停止开发。因此该扩展只支持 PHP5.6 及以前的版本。
现在所使用的都是 PHP memcached 扩展，一个字母 d 之差别。
而 memcached 是基于 libmemcached 开发的， 2.x 和 3.x 分别对应不同的 PHP 版本。
2月14日的更新日志里写的是解决了 memcached 在不同的 PHP 版本下，使用不同的版本来安装的问题。

脚本目前已经修改了安装，不再使用旧的 memcache，而是统一为 memcached。
