### ISSUE TITLE
tried lamp list but command not found?

### ISSUE THREAD

**Issue by majestique** [teddysun/lamp#51]
After installing this on my CentOS 7, I tried the command "lamp list" but it says command not found?

Anyone experiencing the same issue?

**Comment by teddysun** [comment]
Maybe it's not successful installation. something wrong.
Let's check it if you upload your install log.

**Comment by majestique** [comment]
[lamplog.txt](https://github.com/teddysun/lamp/files/1754084/lamplog.txt)

Here's the log file, I just uninstalled it and reinstalled lamp and it still doesn't work.

**Comment by teddysun** [comment]
An error occurred when compiled memcache-3.0.8 from install log.  look #49 #50 
I have fixed that.
Please use latest version and reinstall it.

**Comment by majestique** [comment]
That works! Strange I just downloaded yesterday and it didn't work when the update existed before that.
