### ISSUE TITLE
指定其他版本的php怎么安装

### ISSUE THREAD

**Issue by xdp6688** [teddysun/lamp#56]
指定其他版本的php怎么安装
how to install other php version(7.2.0)

**Comment by teddysun** [comment]
使用 vim 或 nano 打开 include 目录下的 config.sh ，编辑以下这一行
`php7_2_filename="php-7.2.3"`
改为
`php7_2_filename="php-7.2.0"`
保存。
然后，按照正常步骤安装即可。

**Comment by xdp6688** [comment]
谢谢了
