### ISSUE TITLE
Apache Version?

### ISSUE THREAD

**Issue by LaTecnologia24** [teddysun/lamp#60]
1. Upgrade Apache
        2. Upgrade MySQL/MariaDB/Percona
        3. Upgrade PHP
        4. Upgrade phpMyAdmin
        5. Exit

Please input a number: 1
Latest version of Apache:  2.4.29
Installed version of Apache:  2.4.29

Do you want to upgrade Apache ? (y/n)
(Default: n):^C
[root@mysvr lamp]# httpd -v
Server version: Apache/2.4.6 (CentOS)
Server built:   Oct 19 2017 20:39:16
[root@mysvr lamp]# httpd -v
Server version: Apache/2.4.6 (CentOS)
Server built:   Oct 19 2017 20:39:16
[root@mysvr lamp]#

rpm -q httpd
httpd-2.4.6-67.el7.centos.6.x86_64

Apache is 2.4.6 or 2.4.29??

**Comment by teddysun** [comment]
httpd-2.4.6-67.el7.centos.6.x86_64 is default rpm, please uninstall it first.

**Comment by LaTecnologia24** [comment]
I have installed centos and your script, never installed httpd manual or other and your guide never says "unistall"

**Comment by LaTecnologia24** [comment]
I have updated with https://crosp.net/blog/administration/install-latest-apache-server-centos-7/
