### ISSUE TITLE
安装完lamp，打开IP显示forbidden

### ISSUE THREAD

**Issue by chaosye0** [teddysun/lamp#62]
Forbidden

You don't have permission to access / on this server.
不显示lamp页面，也不能进入PHPmyadmin，但是能安装WordPress
系统为centos7

**Comment by chaosye0** [comment]
好像是MySQL的原因，安装MariaDB就没问题。。

**Comment by mindfullsilence** [comment]
编辑虚拟主机配置 /usr/local/apache/conf/vhost/
编辑文件中的文本 `php_admin_value open_basedir /data/www/html:/tmp:/var/tmp:/proc:/data/www/default/phpmyadmin` 改成 `php_admin_value open_basedir /data/www:/tmp:/var/tmp:/proc:/data/www/default/phpmyadmin`

编辑文本是 `/data/www/html` `/data/www`
