### ISSUE TITLE
Installation package libsnmp-dev failed.

### ISSUE THREAD

**Issue by AresDaniel** [teddysun/lamp#65]
+------------------+
|  ERROR DETECTED  |
+------------------+
Installation package libsnmp-dev failed.
The Full Log is available at /root/lamp/lamp.log
Please visit website: https://lamp.sh/faq.html for help

please help me, when i using your script, show me this, and there is a new vps services.

**Comment by AresDaniel** [comment]
------------------------- Install Overview --------------------------

Apache: httpd-2.4.33
Apache Location: /usr/local/apache

Apache Additional Modules:
modsecurity-2.9.2

MariaDB: mariadb-10.2.14
MariaDB Location: /usr/local/mariadb
MariaDB Data Location: /usr/local/mariadb/data
MariaDB Root Password: cloud891021

PHP: php-7.2.4
PHP Location: /usr/local/php
PHP Additional Modules:
gmagick-2.0.5RC1
redis-3.1.6

phpMyAdmin: phpMyAdmin-4.7.9-all-languages
phpMyAdmin Location: /data/www/default/phpmyadmin

**Comment by teddysun** [comment]
`apt-get install libsnmp-dev`
please manually installation, and try again.

**Comment by AresDaniel** [comment]
thanks teddy, Works on it.
