### ISSUE TITLE
Installation package autoconf failed.

### ISSUE THREAD

**Issue by AresDaniel** [teddysun/lamp#66]
[Info] modsecurity-2.9.2 install completed...
[Info] /usr/local/mariadb already exists, skipped the installation.
[Info] Starting to install dependencies packages for PHP...
[Info] Starting to install package autoconf

+------------------+
|  ERROR DETECTED  |
+------------------+
Installation package autoconf failed.
The Full Log is available at /root/lamp/lamp.log
Please visit website: https://lamp.sh/faq.html for help

new issue, this script did not suitable for my server?
need help.
teddy.

**Comment by teddysun** [comment]
Maybe you need install all of dependency packages by manually, and try again.
Or check your server's repo configuration completely.

command like this:
`apt-get install xxxxx`

> autoconf patch m4 bison libbz2-dev libgmp-dev libicu-dev libldb-dev libpam0g-dev
> libldap-2.4-2 libldap2-dev libsasl2-dev libsasl2-modules-ldap libc-client2007e-dev libkrb5-dev
> autoconf2.13 pkg-config libxslt1-dev zlib1g-dev libpcre3-dev libtool unixodbc-dev libtidy-dev
> libjpeg-dev libpng-dev libfreetype6-dev libpspell-dev libmhash-dev libenchant-dev libmcrypt-dev
> libcurl4-gnutls-dev libwebp-dev libxpm-dev libvpx-dev libreadline-dev snmp libsnmp-dev

**Comment by AresDaniel** [comment]
thanks
