### ISSUE TITLE
请问下 主站说的使用提示为什么在安装之后输入会"找不到lamp命令"

### ISSUE THREAD

**Issue by nicklly** [teddysun/lamp#68]
RT 安装后无法按正常提示来进行使用

> lamp add      创建虚拟主机
lamp del      删除虚拟主机
lamp list     列出虚拟主机

**Comment by teddysun** [comment]
出现这种情况，很大的可能是并没有成功安装。
请仔细查看一下安装日志 lamp.log

**Comment by li914** [comment]
楼主 后来怎么安装成功  可以使用lamp命令？？？
