### ISSUE TITLE
Installation package libXpm-devel failed

### ISSUE THREAD

**Issue by josephgrut** [teddysun/lamp#73]
I've got this error first at Ubuntu 16.04 64bit VPS, and then same error at CentOS 6.9 64bit VPS too.

**Comment by josephgrut** [comment]
@teddysun , can you tell how to fix this error?

**Comment by teddysun** [comment]
The package name is libxpm-dev in Ubuntu.
and it is libXpm-devel in CentOS.

Install the libXpm rpm package(CentOS):
`yum install libXpm-devel`

If install failed, please check your system's repo is correct first.
