### ISSUE TITLE
Installation httpd-2.4.33 failed. 

### ISSUE THREAD

**Issue by NAHNAH55** [teddysun/lamp#74]
I got this error: 

mv: cannot move '/home/user/lamp/software/apr-1.6.3' to 'srclib/apr': Permission denied
mv: cannot move '/home/user/lamp/software/apr-util-1.6.1' to 'srclib/apr-util': Permission denied
checking for chosen layout... Apache
checking for working mkdir -p... yes
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
configure: 
configure: Configuring Apache Portable Runtime library...
configure: 
configure: error: Bundled APR requested but not found at ./srclib/. Download and unpack the corresponding apr and apr-util packages to ./srclib/.

Also, the version of rails was downgrade from 5.1 to 4.2 after install. 

Folder permissions are all root, even though I've never signed into root before. 

drwxrwxrwx 0 root root     512 May 23 11:01 server
drwxrwxrwx 0 root root     512 Mar 18 07:41 srclib
drwxrwxrwx 0 root root     512 May 23 11:00 support
drwxrwxrwx 0 root root     512 Mar 18 07:41 test

As a test, even signing into root with sudo su does not fix it. I still get the mv: cannot move error. 

edit: so it seems I was able to install it while signed into room after all, I needed to clear space on my hdd and shut down sublime text editor. But mysql broke completely, I had already installed it manually so during lamp setup I left it unchecked, when lamp finished, it didn't work. I tried purging mysql-server and mysql-client, deleting the folders and re-installing. PHPadmit reported php did not have the mysqli extension enabled, so it seems like lamp doesn't play well with components installed outside of lamp? Is there any way to install stuff manually outside of lamp or is it all or nothing? 

Edit2: After going back through the lamp.sh, just selection mysql, PHPmyAdmin still says 

phpMyAdmin - Error

The mysqli extension is missing. Please check your PHP configuration. See our documentation for more information.

**Comment by developer-variety** [comment]
I can confirm this as this happened to me as well.

**Comment by developer-variety** [comment]
This has still not been resolved?
