### ISSUE TITLE
Teddy: ) here is a question about apache conf file setting problem. 

### ISSUE THREAD

**Issue by AresDaniel** [teddysun/lamp#75]
Thank you for answer this question.
From your website www.lamp.sh there were introduce below: 
"配置文件：
Apache 日志目录： /usr/local/apache/logs
Apache SSL 配置文件： /usr/local/apache/conf/extra/httpd-ssl.conf
**新建站点配置文件： /usr/local/apache/conf/vhost/domain.conf**
PHP 配置文件： /usr/local/php/etc/php.ini
PHP 所有扩展配置文件目录: /usr/local/php/php.d/
MySQL 配置文件： /etc/my.cnf"

But when i finish the instillation found there is only have a file name the none.conf file on this dictionary, this configuration file is empty. here is not have the **domain.conf** 
and i am fist time to using your script on my VPS. PLZ, forgive me asking those shallow problem.
and cloud you introduce carefully from the apache setting configuration for this script.

Daniel.
thanks

**Comment by teddysun** [comment]
Please create your own virtual host first, run command:
`lamp add`
You will find a configuration file when created it.

**Comment by jinzaizhichi** [comment]
lamp add 命令执行失败，求解决方案，谢谢！

**Comment by AresDaniel** [comment]
Okay Teddy thanks.
