### ISSUE TITLE
将phpmyadmin移动到/data/www/vhost目录后提示404错误

### ISSUE THREAD

**Issue by Edelwiess** [teddysun/lamp#76]
phpmyadmin默认在/data/www/default/phpmyadmin下
使用mv命令将phpmyadmin 移动到/data/www/vhost1/phpmyadmin后
访问vhost1.domain1.com/phpmyadmin后提示404错误,找不到vhost1/phpmyadmin
请帮助.

谢谢

**Comment by teddysun** [comment]
你好，请不要移动 phpmyadmin 目录，创建任意虚拟主机后，会自动带一个 Alias 指向 phpmyadmin 的。
在访问的域名后面带上 /phpmyadmin 即可访问。
