### ISSUE TITLE
为什么不能支持内存小于256的呢

### ISSUE THREAD

**Issue by blueyi** [teddysun/lamp#8]
记得以前一直使用你的脚本安装，8月初还安装了，现在安装提示内存不足了，请问如何解决？谢谢，使用你的yum安装脚本也安装了，但安装后phpmyamdin无法打开，打开时提示PHP版本必须>5.5，如何解决。谢谢

**Comment by teddysun** [comment]
内存低于 256MB 的 VPS 在安装过程中最后失败的几率会很大。原因就是内存不足。
脚本的判断逻辑是 RAM + Swap 不能小于 480MB，否则便会退出安装。
也就是说，如果你想在 256MB 的 VPS 上安装，如果其 Swap 也为 256MB 的话，也是能安装成功的。
