### ISSUE TITLE
PHP script being cached

### ISSUE THREAD

**Issue by mranon0007** [teddysun/lamp#83]
I just installed this on my Linux Server and for some reasons the server is loading old php files.
So, I have a php page with following content:

```
<?php
echo uniqid();
```

Now the script prints a unique ID everytime I load the page. The problem is, if I change the contents of the script to something else, the page still prints a uniqid, i.e the old php script is being run. The problem fixes after 30-60 secs though. Can you please tell me what is the cause? I tried disabling browser cache & PHP APC but none of those worked.

**Comment by teddysun** [comment]
Because OPcache extension is enabled.
You can clean up the PHP cache , just access your root URL like below:
example.com/ocp.php
