### ISSUE TITLE
lamp add is not working

### ISSUE THREAD

**Issue by sahnb** [teddysun/lamp#85]
i install on ubuntu Ubuntu 18.04 x64, after complete installation of script alert following error.
libevent-2.0.22-stable failed installation .
when I try command lamp add then the following error :
 
Command 'lamp' not found, did you mean:

  command 'lzmp' from deb lzma
  command 'flamp' from deb flamp
  command 'lamd' from deb lam-runtime
  command 'lame' from deb lame
  command 'pamp' from deb paml

Try: apt install <deb name>

**Comment by jazzi** [comment]
@sahnb you didn't get lamp installed successfully, could you try another fresh install and paste the errors?
