### ISSUE TITLE
ubuntu 18.04.1 not working

### ISSUE THREAD

**Issue by zzeesstt** [teddysun/lamp#87]
Press any key to start...or Press Ctrl+C to cancel

[Info] Starting to sync time...
[Error] ntpdate is not installed, please install it and try again.
_______

root@localhost:# aptitude install ntpdate
Couldn't find any package whose name or description matched "ntpdate"
Unable to apply some actions, aborting
root@localhost:#

**Comment by teddysun** [comment]
apt-get -y update
apt-get -y install ntpdate

**Comment by zzeesstt** [comment]
teddysun, There is no such package in the repository
"E: The ntpdate package could not be found"

**Comment by teddysun** [comment]
`ntpdate` linux package at Ubuntu 18.04 is exist.
[https://pkgs.org/download/ntpdate](https://pkgs.org/download/ntpdate)

**Comment by zzeesstt** [comment]
really works)))
Thank you!

**Comment by zzeesstt** [comment]
[^[[0;32mInfo^[[0m] Starting to install package ntpdate
[^[[0;32mInfo^[[0m] Install development tools completed...
[^[[0;32mInfo^[[0m] Starting to sync time...
 9 Sep 14:44:52 ntpdate[879]: ntpdate 4.2.8p10@1.3728-o (1)
 9 Sep 14:45:00 ntpdate[879]: step time server 193.228.143.12 offset 0.000398 sec
[^[[0;32mInfo^[[0m] Sync time completed...
[^[[0;32mInfo^[[0m] Starting remove the conflict packages...
[^[[0;32mInfo^[[0m] Remove the conflict packages completed...
[^[[0;32mInfo^[[0m] Starting to install dependencies packages for Apache...
[^[[0;32mInfo^[[0m] Starting to install package openssl
[^[[0;32mInfo^[[0m] Starting to install package libssl-dev
[^[[0;32mInfo^[[0m] Starting to install package libxml2-dev
[^[[0;32mInfo^[[0m] Starting to install package lynx

+------------------+
|  ERROR DETECTED  |
+------------------+
Installation package lynx failed.
The Full Log is available at /root/lamp/lamp.log
Please visit website: https://lamp.sh/faq.html for help

**Comment by shohanshohan** [comment]
@zzeesstt I have the same problem ,in ubuntu18.04 not work . so i use ubuntu16.04

**Comment by teddysun** [comment]
`lynx` package at Ubuntu 18.04 is exist.
https://ubuntu.pkgs.org/18.04/ubuntu-universe-amd64/lynx_2.8.9dev16-3_amd64.deb.html
