### ISSUE TITLE
dl.lamp.sh, have some problem??

### ISSUE THREAD

**Issue by feanlau** [teddysun/lamp#93]
`
Resolving dl.lamp.sh (dl.lamp.sh)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘dl.lamp.sh’
[Error] Failed to download re2c-1.0.2.tar.gz, please download it to /root/lamp/software directory manually and try again.
`

**Comment by teddysun** [comment]
Now it's return to normal.
Thanks for your feedback.

**Comment by feanlau** [comment]
Thank you for you good work!!!
