### ISSUE TITLE
MySQL 5.5无法升级到5.6

### ISSUE THREAD

**Issue by jazzi** [teddysun/lamp#94]
./upgrade db

已安装版本为5.5.6，无法升级到5.6或者7.0

**Comment by teddysun** [comment]
这不是 bug。
升级的脚本，逻辑就是考虑到同版本升级，而不是跨版本升级。

**Comment by jazzi** [comment]
请问有办法提供跨版本升级吗？因为现在有些软件的版本要求比较高，不升级的话就无法安装。
