### ISSUE TITLE
PHP 升级失败

### ISSUE THREAD

**Issue by jazzi** [teddysun/lamp#97]
因为内存不足，php升级时安装内存被kill，增加内存后再执行./upgrade.sh php，出现下面错误，无法升级。

> PHP looks like not installed, please check it and try again

不知是否之前升级失败遗留的问题。

**Comment by teddysun** [comment]
这是升级保护机制造成的。
升级的时候会先把原来的 php 安装目录重命名为 /usr/local/php.bak
安装失败后，没有再次重命名回来导致的（后续打算修正这个问题，失败后自动重命名回来）
因此你需要先手动将 /usr/local/php.bak 重命名为 /usr/local/php，然后再次重试升级脚本即可。
`mv /usr/local/php.bak /usr/local/php`

**Comment by jazzi** [comment]
问题解决了，谢谢你。
