### ISSUE TITLE
Installation package libreadline-dev failed

### ISSUE THREAD

**Issue by Chriswyp** [teddysun/lamp#98]
你好，我在virtualbox上装的debian 9，在安装你的lamp时，报错 Installation package libreadline-dev failed。系统里已经有了libreadline7.0-3的包了，是因为这个安装不上你这要装的libreadline6吗
sudo apt-get install libreadline-dev
报出：没有可用的软件包 libreadline-dev，但是它被其它的软件包引用了。
或者只能在其他发布源中找到

**Comment by shidachuang** [comment]
同问

**Comment by Chriswyp** [comment]
已经解决了
重新装了debian 9系统，改用了kde桌面，然后做了次系统升级，那个问题就没了
